In [1]:
import pandas as pd
import numpy as np

In [2]:
ccn_data = pd.read_csv('fillter/all18-0.5-NaN.csv', sep=',',skiprows=0,header=0,na_values=[9999])

In [3]:
ccn_data.head()

,lat_bin,lon_bin,winNO,big_c,big_r,lat,lon,colum,row,Have,...,AMR_surf,SMR_surf,T_LCL_surf,H_LCL_lowest,AMR_lowest,SMR_lowest,T_LCL_lowest,CAPE_surf,CAPE_lowest,Tb_f
0,10.0,123.5,1204.500000,2944.0,6144.0,10.279550,123.714100,2896.0,6048.0,95.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.500000
1,10.0,124.0,1103.000000,3232.0,6144.0,10.044900,124.300800,3040.0,6144.0,64.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.000000
2,10.0,124.5,1102.333333,3232.0,6144.0,10.235567,124.839967,3200.0,6112.0,118.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.666667
3,10.0,125.0,1003.000000,3520.0,6144.0,10.199000,125.310800,3328.0,6144.0,38.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.000000
4,10.0,125.5,1002.000000,3520.0,6144.0,10.249800,125.649500,3424.0,6144.0,63.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.000000

In [6]:
data1=ccn_data

In [ ]:
step = 0.5
to_bin = lambda x: np.floor(x / step) * step
data1["lat_bin"] = data1.lat.map(to_bin)
data1["lon_bin"] = data1.lon.map(to_bin)
groups = data1.groupby(("lat_bin", "lon_bin"))
#avg_data=all_data.set_index(['latbin', 'lonbin']).stack().groupby(level=[0, 1]).mean()
avg_data=data1.groupby(['lat_bin','lon_bin']).count()
print(avg_data.head())

In [ ]:
avg_data.to_csv("count_CCN.csv",index=True,sep=',')

In [ ]:
import os, time, datetime
from datetime import datetime
import matplotlib.pyplot as plt
from matplotlib import cm as CM
from matplotlib.colors import LogNorm,PowerNorm
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.io.shapereader import Reader
import matplotlib.ticker as mticker
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import cmocean

In [ ]:
def plotMap():
    #Set the projection information Cannot label gridlines on a LambertConformal plot. Only PlateCarree and Mercator plots are currently supported.
##add shapefile
    # add borders, coastline, rivers, lakes, and provinces of China
    proj = ccrs.PlateCarree(central_longitude=118.8)
    #Create a figure with an axes object on which we will plot. Pass the projection to that axes.
    fig, ax = plt.subplots(figsize=(11.8, 8),subplot_kw=dict(projection=proj))
    #ax.background_img(name='BM', resolution='high')
    #Zoom in
    ax.set_extent([105, 130, 20, 46])

    #Add map features
    ax.add_feature(cfeature.LAND, facecolor='0.99') #Grayscale colors can be set using 0 (black) to 1 (white)
    ax.add_feature(cfeature.LAKES, alpha=0.9)  #Alpha sets transparency (0 is transparent, 1 is solid)
    ax.add_feature(cfeature.BORDERS.with_scale('10m'), zorder=10, linestyle=':') # high resolution
    ax.add_feature(cfeature.COASTLINE.with_scale('50m'), zorder=10, linestyle=':') # mediate resolution
    ax.add_feature(cfeature.RIVERS) # low resolution
    #ax.stock_img()

    #We can use additional features from Natural Earth (http://www.naturalearthdata.com/features/)
    states_provinces = cfeature.NaturalEarthFeature(
            category='cultural',  name='admin_1_states_provinces_lines',
            scale='50m',facecolor='none')
    ax.add_feature(states_provinces, edgecolor='gray', zorder=10)
    fname = 'D:\data\map\CHN_adm1.shp'
    adm1_shapes = list(Reader(fname).geometries())
    ax.add_geometries(adm1_shapes, crs=ccrs.PlateCarree(),edgecolor='black', facecolor='none', alpha=0.5,linewidths=0.5)
    newcmap = cmocean.tools.crop_by_percent(cmocean.cm.balance, 1, which='both', N=20)
    plt.scatter(lon,lat,#latlon=True,
          c=ccn,
          #cmap=newcmap,norm=PowerNorm(gamma=0.7),alpha=0.5,transform=ccrs.PlateCarree()) #Normalize a given value to the 0-1 range on a log scale
          #cmap=CM.get_cmap('rainbow',40),norm=LogNorm(vmin=max(ccn.min(),0.1),clip=True),alpha=0.5,transform=ccrs.PlateCarree()) #Normalize a given value to the 0-1 range on a log scale
          cmap=newcmap,alpha=0.8,transform=ccrs.PlateCarree()) #Normalize a given value to the 0-1 range on a log scale
    #Add lat/lon gridlines every 20Â° to the map
    plt.colorbar(label=r'CCN/cm^3')
    plt.clim(0,150)
# make legend with dummy points
    plt.title("2013-2018 Summer", fontsize=20)
    return fig, ax

In [ ]:
# Extract the data we're interested in
lat=avg_data.index.get_level_values(0)
lon=avg_data.index.get_level_values(1)
ccn = avg_data['CCN_1.0_cm3'].values
lat_max=np.nanmax(lat)
lon_max=np.nanmax(lon)
lat_min=np.nanmin(lat)
lon_min=np.nanmin(lon)
ccn_max=np.nanmax(ccn)
print(ccn_max)
ccn_min=np.nanmin(ccn)
print(ccn_min)

fig, ax= plotMap()
plt.savefig('count_CCN.png',dpi=200)

In [ ]:
data_10=avg_data[avg_data['CCN_1.0_cm3']>=10]

In [ ]:
ccn= data_10['CCN_1.0_cm3'].values

In [ ]:
lat=data_10.index.get_level_values(0)
lon=data_10.index.get_level_values(1)

In [ ]:
lat_max=np.nanmax(lat)
lon_max=np.nanmax(lon)
lat_min=np.nanmin(lat)
lon_min=np.nanmin(lon)
ccn_max=np.nanmax(ccn)
print(ccn_max)
ccn_min=np.nanmin(ccn)
print(ccn_min)

In [ ]:
fig, ax= plotMap()
plt.savefig('count_CCN10.png',dpi=200)