In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib import cm as CM
from matplotlib.colors import LogNorm,PowerNorm
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.io.shapereader import Reader
import matplotlib.ticker as mticker
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
from shapely.geometry import *
from scipy.interpolate import griddata
import cmocean

In [3]:
fp = "D:/data/map/prd_9city.shp" #生成的坐标不对
mapfile = gpd.read_file(fp,encoding='gbk')

In [4]:
mapfile

,ID_0,ISO,NAME_0,ID_1,NAME_1,ID_2,NAME_2,VARNAME_2,NL_NAME_2,HASC_2,CC_2,TYPE_2,ENGTYPE_2,VALIDFR_2,VALIDTO_2,REMARKS_2,Shape_Leng,Shape_Area,geometry
0,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,6.049119,0.630133,(POLYGON ((113.6270840000001 22.72736200000008...
1,45,CHN,China,576,Guangdong,9811,Huizhou,Hu锟絲hou,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,9.867862,0.997726,(POLYGON ((114.8334730000001 22.51375000000002...
2,45,CHN,China,576,Guangdong,9812,Jiangmen,Jiangm锟絥,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,10.246350,0.822387,"(POLYGON ((112.810143 21.58236100000005, 112.8..."
3,45,CHN,China,576,Guangdong,9807,Dongguan,Dongguan,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,2.794603,0.212934,"POLYGON ((113.7502300000001 23.13159400000012,..."
4,45,CHN,China,576,Guangdong,9808,Foshan,F锟絪han,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,4.464386,0.342003,"POLYGON ((112.877854 23.56911800000012, 112.88..."
5,45,CHN,China,576,Guangdong,9820,Shenzhen,Shenzh锟絥,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,5.365538,0.168399,(POLYGON ((114.6665270000001 22.40847199999996...
6,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,6.746065,1.314538,"POLYGON ((112.30918 24.37709799999999, 112.318..."
7,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,2.062425,0.154312,"POLYGON ((113.4164960000001 22.739847, 113.423..."
8,45,CHN,China,576,Guangdong,9826,Zhuhai,Zhuhai,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,9.575177,0.131368,(POLYGON ((113.9743050000001 21.82319500000011...

In [5]:
data = pd.read_csv('C:/Users/xigrug/Desktop/CCN/avg_CCNnew.csv', sep=',',skiprows=0,header=0)

In [6]:
data

,lat_bin,lon_bin,BJC,AMR_lowest,AMR_surf,AOD,B4LI,CAPE,CAPE_lowest,CAPE_nc,...,satz,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid
0,26.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2121.000000,...,-12.100,14.905000,NaN,NaN,NaN,363.000000,1.000000,363.500000,1203.500000,26.0117.5
1,26.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2048.666667,...,-8.220,15.370000,NaN,NaN,NaN,592.666667,0.996667,594.666667,1170.333333,26.0118.0
2,26.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,-4.830,15.755000,NaN,NaN,NaN,452.500000,1.000000,452.500000,1102.500000,26.0118.5
3,26.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,-0.480,16.260000,NaN,NaN,NaN,171.000000,1.000000,171.000000,1101.000000,26.0119.0
4,26.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2121.000000,...,-12.100,14.930000,NaN,NaN,NaN,1885.000000,1.000000,1885.000000,1208.000000,26.5117.5
5,26.5,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2012.500000,...,-7.735,15.450000,NaN,NaN,NaN,596.500000,1.000000,596.500000,1158.000000,26.5118.0
6,26.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-3.375,15.940000,NaN,NaN,NaN,477.000000,0.980000,491.500000,1106.500000,26.5118.5
7,26.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-0.475,16.280000,NaN,NaN,NaN,584.500000,1.000000,584.500000,1105.500000,26.5119.0
8,27.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,1904.000000,...,-6.280,15.655000,NaN,NaN,NaN,3658.000000,1.000000,3659.000000,3304.500000,27.0118.0
9,27.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-3.380,15.995000,NaN,NaN,NaN,1297.500000,1.000000,1298.500000,3303.500000,27.0118.5
10,27.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-0.480,16.310000,NaN,NaN,NaN,718.000000,1.000000,718.000000,3301.000000,27.0119.0
11,27.0,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.20,812.0,NaN,941.000000,...,28.890,19.910000,NaN,NaN,NaN,1652.000000,1.000000,1652.000000,709.000000,27.0123.0
12,27.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.60,1119.0,NaN,667.000000,...,48.060,23.200000,NaN,NaN,NaN,891.000000,1.010000,880.000000,501.000000,27.0126.5
13,27.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,...,-12.100,15.050000,NaN,NaN,NaN,2395.000000,0.985000,2449.500000,4505.000000,27.5117.0
14,27.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2323.000000,...,-9.190,15.395000,NaN,NaN,NaN,3088.000000,1.170000,2728.000000,4504.000000,27.5117.5
15,27.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1904.000000,...,-0.480,16.355000,NaN,NaN,NaN,2999.000000,0.975000,3064.000000,3305.500000,27.5118.5
16,27.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1631.000000,...,2.470,16.690000,NaN,NaN,NaN,3058.000000,1.000000,3059.500000,3207.500000,27.5119.0
17,27.5,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,28.890,19.930000,NaN,NaN,NaN,788.000000,0.950000,833.000000,2903.000000,27.5123.0
18,27.5,123.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.80,559.0,NaN,749.000000,...,31.900,20.360000,NaN,NaN,NaN,296.000000,1.000000,296.000000,1805.000000,27.5123.5
19,28.0,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,...,-12.100,15.120000,NaN,NaN,NaN,3786.000000,1.000000,3777.000000,5605.000000,28.0117.0
20,28.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2094.500000,...,-7.735,15.630000,NaN,NaN,NaN,5353.000000,1.000000,5353.000000,5555.000000,28.0117.5
21,28.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2081.000000,...,-4.830,15.915000,NaN,NaN,NaN,5609.000000,0.920000,6080.500000,5502.500000,28.0118.0
22,28.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,2081.000000,...,-0.480,16.440000,NaN,NaN,NaN,2661.500000,0.945000,2799.500000,5502.500000,28.0118.5
23,28.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1551.000000,...,2.470,16.750000,NaN,NaN,NaN,411.000000,0.970000,422.000000,5403.000000,28.0119.0
24,28.0,119.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.90,1670.0,NaN,1551.000000,...,8.270,17.410000,NaN,NaN,NaN,827.000000,1.000000,827.000000,5401.000000,28.0119.5
25,28.0,122.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,28.890,19.980000,NaN,NaN,NaN,1010.000000,0.720000,1405.000000,2909.000000,28.0122.5
26,28.0,125.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,43.760,22.390000,NaN,NaN,NaN,4333.000000,0.870000,4990.000000,2706.000000,28.0125.5
27,28.0,126.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,45.900,22.810000,NaN,NaN,NaN,3949.000000,0.910000,4326.000000,2705.000000,28.0126.0
28,28.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.90,515.0,NaN,667.000000,...,48.060,23.250000,NaN,NaN,NaN,2808.500000,0.960000,2949.000000,2702.500000,28.0126.5
29,28.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-2.10,752.0,NaN,1621.666667,...,-10.160,15.426667,NaN,NaN,NaN,6812.000000,1.000000,6812.000000,6338.666667,28.5117.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76906,35.0,123.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2033.0,NaN,1075.000000,...,2.460,29.740000,NaN,NaN,NaN,845.000000,1.000000,845.000000,42803.000000,35.0123.5
76907,35.0,124.0,2018-08-30 04:42:00,NaN,NaN,NaN,-5.40,2061.0,NaN,1075.000000,...,5.360,29.970000,NaN,NaN,NaN,675.000000,1.000000,675.000000,42802.000000,35.0124.0
76908,35.0,124.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.80,1686.0,NaN,1242.000000,...,11.180,30.440000,NaN,NaN,NaN,1112.000000,1.000000,1112.000000,42703.000000,35.0124.5
76909,35.0,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.65,1711.5,NaN,1276.000000,...,14.100,30.565000,NaN,NaN,NaN,2437.000000,1.000000,2437.000000,41605.000000,35.0125.0
76910,35.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1320.0,NaN,1864.000000,...,22.930,31.240000,NaN,NaN,NaN,1782.000000,1.000000,1782.000000,40408.000000,35.0126.5
76911,35.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.60,1222.0,NaN,1373.000000,...,34.940,32.280000,NaN,NaN,NaN,78.000000,1.000000,78.000000,40304.000000,35.0128.5
76912,35.5,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.20,1377.0,NaN,1170.000000,...,-12.110,29.370000,NaN,NaN,NaN,661.000000,1.000000,661.000000,45202.000000,35.5121.0
76913,35.5,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1425.0,NaN,1242.000000,...,14.100,30.910000,NaN,NaN,NaN,2670.000000,1.000000,2670.000000,42705.000000,35.5125.0
76914,35.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1221.0,NaN,1408.000000,...,22.920,31.460000,NaN,NaN,NaN,3193.000000,1.000000,3193.000000,42602.000000,35.5126.5
76915,35.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.25,1838.0,NaN,1629.500000,...,34.940,32.595000,NaN,NaN,NaN,3678.000000,1.000000,3683.000000,41404.000000,35.5128.5
76916,35.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.60,1750.0,NaN,1594.000000,...,37.500,33.010000,NaN,NaN,NaN,556.000000,1.000000,557.000000,42403.000000,35.5129.0
76917,36.0,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,517.5,NaN,1170.000000,...,-12.110,29.735000,NaN,NaN,NaN,1930.000000,0.960000,1943.000000,45206.500000,36.0121.0
76918,36.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.40,1316.0,NaN,1408.000000,...,25.900,32.190000,NaN,NaN,NaN,4450.000000,0.970000,4571.000000,42607.000000,36.0127.0
76919,36.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.15,1333.5,NaN,1886.000000,...,28.885,32.370000,NaN,NaN,NaN,2245.500000,0.940000,2421.000000,42507.500000,36.0127.5
76920,36.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1779.0,NaN,1886.000000,...,31.900,32.690000,NaN,NaN,NaN,3705.500000,1.000000,3709.500000,42506.500000,36.0128.0
76921,36.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1754.0,NaN,1886.000000,...,34.940,32.920000,NaN,NaN,NaN,4548.000000,1.000000,4548.000000,42504.000000,36.0128.5
76922,36.5,121.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.75,300.5,NaN,1142.500000,...,-7.745,30.180000,NaN,NaN,NaN,2487.500000,0.995000,2494.000000,45158.000000,36.5121.5
76923,36.5,122.0,2018-08-30 04:42:00,NaN,NaN,NaN,-1.70,0.0,NaN,1115.000000,...,-3.380,30.500000,NaN,NaN,NaN,730.000000,1.000000,730.000000,45108.000000,36.5122.0
76924,36.5,122.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.80,0.0,NaN,1115.000000,...,-0.480,30.710000,NaN,NaN,NaN,747.000000,1.000000,747.000000,45107.000000,36.5122.5
76925,36.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1328.5,NaN,246.000000,...,25.900,32.525000,NaN,NaN,NaN,1799.500000,1.000000,1799.000000,44802.500000,36.5126.5
76926,36.5,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1485.0,NaN,1437.000000,...,28.890,32.710000,NaN,NaN,NaN,4552.000000,0.980000,4644.000000,44703.000000,36.5127.0
76927,36.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1536.0,NaN,1886.000000,...,34.940,33.140000,NaN,NaN,NaN,2820.000000,0.980000,2879.000000,42507.000000,36.5128.5
76928,36.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.00,1457.0,NaN,1314.000000,...,37.490,33.650000,NaN,NaN,NaN,1772.000000,1.000000,1776.000000,44603.000000,36.5129.0
76929,36.5,129.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2236.0,NaN,1594.000000,...,39.560,33.700000,NaN,NaN,NaN,563.000000,0.920000,613.000000,42408.000000,36.5129.5
76930,37.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,192.0,NaN,246.000000,...,25.900,32.870000,NaN,NaN,NaN,4359.000000,0.990000,4399.000000,44807.000000,37.0126.5
76931,37.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1302.5,NaN,1437.000000,...,28.890,33.040000,NaN,NaN,NaN,4474.500000,0.935000,4724.500000,44707.500000,37.0127.0
76932,37.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1567.5,NaN,1437.000000,...,31.900,33.350000,NaN,NaN,NaN,4152.000000,0.925000,4449.000000,44706.500000,37.0127.5
76933,37.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,781.0,NaN,1437.000000,...,34.940,33.790000,NaN,NaN,NaN,7740.000000,1.000000,7740.000000,44707.000000,37.0128.0
76934,37.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,825.0,NaN,1437.000000,...,34.940,33.570000,NaN,NaN,NaN,5428.000000,1.000000,5428.000000,44704.000000,37.0128.5
76935,37.0,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.80,1380.0,NaN,1314.000000,...,37.490,33.870000,NaN,NaN,NaN,3439.000000,1.000000,3456.000000,44606.000000,37.0129.0

In [7]:
data['Coordinates'] = list(zip(data.lon_bin, data.lat_bin))
data['Coordinates'] = data['Coordinates'].apply(Point)

In [8]:
# get geo data
gdf = gpd.GeoDataFrame(data, geometry='Coordinates')
gdf.crs = mapfile.crs
#gdf=gdf.dropna(subset=[ '2001'])#Remember to reassign
cities_with_country = gpd.sjoin(mapfile,gdf,how="inner", op='intersects')
#print(df1)
#df1.to_csv("cities_with_country.csv")

In [9]:
gdf

,lat_bin,lon_bin,BJC,AMR_lowest,AMR_surf,AOD,B4LI,CAPE,CAPE_lowest,CAPE_nc,...,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid,Coordinates
0,26.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2121.000000,...,14.905000,NaN,NaN,NaN,363.000000,1.000000,363.500000,1203.500000,26.0117.5,POINT (117.5 26)
1,26.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2048.666667,...,15.370000,NaN,NaN,NaN,592.666667,0.996667,594.666667,1170.333333,26.0118.0,POINT (118 26)
2,26.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,15.755000,NaN,NaN,NaN,452.500000,1.000000,452.500000,1102.500000,26.0118.5,POINT (118.5 26)
3,26.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,16.260000,NaN,NaN,NaN,171.000000,1.000000,171.000000,1101.000000,26.0119.0,POINT (119 26)
4,26.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2121.000000,...,14.930000,NaN,NaN,NaN,1885.000000,1.000000,1885.000000,1208.000000,26.5117.5,POINT (117.5 26.5)
5,26.5,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2012.500000,...,15.450000,NaN,NaN,NaN,596.500000,1.000000,596.500000,1158.000000,26.5118.0,POINT (118 26.5)
6,26.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,15.940000,NaN,NaN,NaN,477.000000,0.980000,491.500000,1106.500000,26.5118.5,POINT (118.5 26.5)
7,26.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,16.280000,NaN,NaN,NaN,584.500000,1.000000,584.500000,1105.500000,26.5119.0,POINT (119 26.5)
8,27.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,1904.000000,...,15.655000,NaN,NaN,NaN,3658.000000,1.000000,3659.000000,3304.500000,27.0118.0,POINT (118 27)
9,27.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,15.995000,NaN,NaN,NaN,1297.500000,1.000000,1298.500000,3303.500000,27.0118.5,POINT (118.5 27)
10,27.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,16.310000,NaN,NaN,NaN,718.000000,1.000000,718.000000,3301.000000,27.0119.0,POINT (119 27)
11,27.0,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.20,812.0,NaN,941.000000,...,19.910000,NaN,NaN,NaN,1652.000000,1.000000,1652.000000,709.000000,27.0123.0,POINT (123 27)
12,27.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.60,1119.0,NaN,667.000000,...,23.200000,NaN,NaN,NaN,891.000000,1.010000,880.000000,501.000000,27.0126.5,POINT (126.5 27)
13,27.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,...,15.050000,NaN,NaN,NaN,2395.000000,0.985000,2449.500000,4505.000000,27.5117.0,POINT (117 27.5)
14,27.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2323.000000,...,15.395000,NaN,NaN,NaN,3088.000000,1.170000,2728.000000,4504.000000,27.5117.5,POINT (117.5 27.5)
15,27.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1904.000000,...,16.355000,NaN,NaN,NaN,2999.000000,0.975000,3064.000000,3305.500000,27.5118.5,POINT (118.5 27.5)
16,27.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1631.000000,...,16.690000,NaN,NaN,NaN,3058.000000,1.000000,3059.500000,3207.500000,27.5119.0,POINT (119 27.5)
17,27.5,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,19.930000,NaN,NaN,NaN,788.000000,0.950000,833.000000,2903.000000,27.5123.0,POINT (123 27.5)
18,27.5,123.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.80,559.0,NaN,749.000000,...,20.360000,NaN,NaN,NaN,296.000000,1.000000,296.000000,1805.000000,27.5123.5,POINT (123.5 27.5)
19,28.0,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,...,15.120000,NaN,NaN,NaN,3786.000000,1.000000,3777.000000,5605.000000,28.0117.0,POINT (117 28)
20,28.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2094.500000,...,15.630000,NaN,NaN,NaN,5353.000000,1.000000,5353.000000,5555.000000,28.0117.5,POINT (117.5 28)
21,28.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2081.000000,...,15.915000,NaN,NaN,NaN,5609.000000,0.920000,6080.500000,5502.500000,28.0118.0,POINT (118 28)
22,28.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,2081.000000,...,16.440000,NaN,NaN,NaN,2661.500000,0.945000,2799.500000,5502.500000,28.0118.5,POINT (118.5 28)
23,28.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1551.000000,...,16.750000,NaN,NaN,NaN,411.000000,0.970000,422.000000,5403.000000,28.0119.0,POINT (119 28)
24,28.0,119.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.90,1670.0,NaN,1551.000000,...,17.410000,NaN,NaN,NaN,827.000000,1.000000,827.000000,5401.000000,28.0119.5,POINT (119.5 28)
25,28.0,122.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,19.980000,NaN,NaN,NaN,1010.000000,0.720000,1405.000000,2909.000000,28.0122.5,POINT (122.5 28)
26,28.0,125.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,22.390000,NaN,NaN,NaN,4333.000000,0.870000,4990.000000,2706.000000,28.0125.5,POINT (125.5 28)
27,28.0,126.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,22.810000,NaN,NaN,NaN,3949.000000,0.910000,4326.000000,2705.000000,28.0126.0,POINT (126 28)
28,28.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.90,515.0,NaN,667.000000,...,23.250000,NaN,NaN,NaN,2808.500000,0.960000,2949.000000,2702.500000,28.0126.5,POINT (126.5 28)
29,28.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-2.10,752.0,NaN,1621.666667,...,15.426667,NaN,NaN,NaN,6812.000000,1.000000,6812.000000,6338.666667,28.5117.0,POINT (117 28.5)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76906,35.0,123.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2033.0,NaN,1075.000000,...,29.740000,NaN,NaN,NaN,845.000000,1.000000,845.000000,42803.000000,35.0123.5,POINT (123.5 35)
76907,35.0,124.0,2018-08-30 04:42:00,NaN,NaN,NaN,-5.40,2061.0,NaN,1075.000000,...,29.970000,NaN,NaN,NaN,675.000000,1.000000,675.000000,42802.000000,35.0124.0,POINT (124 35)
76908,35.0,124.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.80,1686.0,NaN,1242.000000,...,30.440000,NaN,NaN,NaN,1112.000000,1.000000,1112.000000,42703.000000,35.0124.5,POINT (124.5 35)
76909,35.0,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.65,1711.5,NaN,1276.000000,...,30.565000,NaN,NaN,NaN,2437.000000,1.000000,2437.000000,41605.000000,35.0125.0,POINT (125 35)
76910,35.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1320.0,NaN,1864.000000,...,31.240000,NaN,NaN,NaN,1782.000000,1.000000,1782.000000,40408.000000,35.0126.5,POINT (126.5 35)
76911,35.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.60,1222.0,NaN,1373.000000,...,32.280000,NaN,NaN,NaN,78.000000,1.000000,78.000000,40304.000000,35.0128.5,POINT (128.5 35)
76912,35.5,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.20,1377.0,NaN,1170.000000,...,29.370000,NaN,NaN,NaN,661.000000,1.000000,661.000000,45202.000000,35.5121.0,POINT (121 35.5)
76913,35.5,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1425.0,NaN,1242.000000,...,30.910000,NaN,NaN,NaN,2670.000000,1.000000,2670.000000,42705.000000,35.5125.0,POINT (125 35.5)
76914,35.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1221.0,NaN,1408.000000,...,31.460000,NaN,NaN,NaN,3193.000000,1.000000,3193.000000,42602.000000,35.5126.5,POINT (126.5 35.5)
76915,35.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.25,1838.0,NaN,1629.500000,...,32.595000,NaN,NaN,NaN,3678.000000,1.000000,3683.000000,41404.000000,35.5128.5,POINT (128.5 35.5)
76916,35.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.60,1750.0,NaN,1594.000000,...,33.010000,NaN,NaN,NaN,556.000000,1.000000,557.000000,42403.000000,35.5129.0,POINT (129 35.5)
76917,36.0,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,517.5,NaN,1170.000000,...,29.735000,NaN,NaN,NaN,1930.000000,0.960000,1943.000000,45206.500000,36.0121.0,POINT (121 36)
76918,36.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.40,1316.0,NaN,1408.000000,...,32.190000,NaN,NaN,NaN,4450.000000,0.970000,4571.000000,42607.000000,36.0127.0,POINT (127 36)
76919,36.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.15,1333.5,NaN,1886.000000,...,32.370000,NaN,NaN,NaN,2245.500000,0.940000,2421.000000,42507.500000,36.0127.5,POINT (127.5 36)
76920,36.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1779.0,NaN,1886.000000,...,32.690000,NaN,NaN,NaN,3705.500000,1.000000,3709.500000,42506.500000,36.0128.0,POINT (128 36)
76921,36.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1754.0,NaN,1886.000000,...,32.920000,NaN,NaN,NaN,4548.000000,1.000000,4548.000000,42504.000000,36.0128.5,POINT (128.5 36)
76922,36.5,121.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.75,300.5,NaN,1142.500000,...,30.180000,NaN,NaN,NaN,2487.500000,0.995000,2494.000000,45158.000000,36.5121.5,POINT (121.5 36.5)
76923,36.5,122.0,2018-08-30 04:42:00,NaN,NaN,NaN,-1.70,0.0,NaN,1115.000000,...,30.500000,NaN,NaN,NaN,730.000000,1.000000,730.000000,45108.000000,36.5122.0,POINT (122 36.5)
76924,36.5,122.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.80,0.0,NaN,1115.000000,...,30.710000,NaN,NaN,NaN,747.000000,1.000000,747.000000,45107.000000,36.5122.5,POINT (122.5 36.5)
76925,36.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1328.5,NaN,246.000000,...,32.525000,NaN,NaN,NaN,1799.500000,1.000000,1799.000000,44802.500000,36.5126.5,POINT (126.5 36.5)
76926,36.5,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1485.0,NaN,1437.000000,...,32.710000,NaN,NaN,NaN,4552.000000,0.980000,4644.000000,44703.000000,36.5127.0,POINT (127 36.5)
76927,36.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1536.0,NaN,1886.000000,...,33.140000,NaN,NaN,NaN,2820.000000,0.980000,2879.000000,42507.000000,36.5128.5,POINT (128.5 36.5)
76928,36.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.00,1457.0,NaN,1314.000000,...,33.650000,NaN,NaN,NaN,1772.000000,1.000000,1776.000000,44603.000000,36.5129.0,POINT (129 36.5)
76929,36.5,129.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2236.0,NaN,1594.000000,...,33.700000,NaN,NaN,NaN,563.000000,0.920000,613.000000,42408.000000,36.5129.5,POINT (129.5 36.5)
76930,37.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,192.0,NaN,246.000000,...,32.870000,NaN,NaN,NaN,4359.000000,0.990000,4399.000000,44807.000000,37.0126.5,POINT (126.5 37)
76931,37.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1302.5,NaN,1437.000000,...,33.040000,NaN,NaN,NaN,4474.500000,0.935000,4724.500000,44707.500000,37.0127.0,POINT (127 37)
76932,37.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1567.5,NaN,1437.000000,...,33.350000,NaN,NaN,NaN,4152.000000,0.925000,4449.000000,44706.500000,37.0127.5,POINT (127.5 37)
76933,37.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,781.0,NaN,1437.000000,...,33.790000,NaN,NaN,NaN,7740.000000,1.000000,7740.000000,44707.000000,37.0128.0,POINT (128 37)
76934,37.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,825.0,NaN,1437.000000,...,33.570000,NaN,NaN,NaN,5428.000000,1.000000,5428.000000,44704.000000,37.0128.5,POINT (128.5 37)
76935,37.0,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.80,1380.0,NaN,1314.000000,...,33.870000,NaN,NaN,NaN,3439.000000,1.000000,3456.000000,44606.000000,37.0129.0,POINT (129 37)

In [10]:
cities_with_country = gpd.sjoin(mapfile,gdf,how="inner", op='intersects')

In [11]:
cities_with_country=cities_with_country.drop(["geometry"],axis=1)

In [13]:
cities_with_country.to_csv("prd_ccn_new.csv")

In [14]:
df=pd.read_csv("prd_ccn_new.csv")

In [15]:
df.head()

,Unnamed: 0,ID_0,ISO,NAME_0,ID_1,NAME_1,ID_2,NAME_2,VARNAME_2,NL_NAME_2,...,satz,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid
0,0,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,...,-0.48,18.875,NaN,NaN,NaN,3202.5,1.0,3202.5,31902.5,23.5113.5
1,0,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,...,-12.11,14.470,NaN,NaN,NaN,1738.5,1.0,1738.5,1206.5,23.5113.5
2,0,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,...,-0.48,16.200,NaN,NaN,NaN,359.0,1.0,359.0,16501.0,23.5113.5
3,0,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,...,-12.10,17.985,NaN,NaN,NaN,1161.0,1.0,1161.0,14406.5,23.5113.5
4,0,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,...,-12.10,15.090,NaN,NaN,NaN,279.0,1.0,279.0,32002.0,23.5113.5

In [16]:
df=df.drop(["Unnamed: 0"],axis=1)

In [17]:
df

,ID_0,ISO,NAME_0,ID_1,NAME_1,ID_2,NAME_2,VARNAME_2,NL_NAME_2,HASC_2,...,satz,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid
0,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-0.480000,18.875000,NaN,NaN,NaN,3202.500000,1.000000,3202.500000,31902.500000,23.5113.5
1,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,14.470000,NaN,NaN,NaN,1738.500000,1.000000,1738.500000,1206.500000,23.5113.5
2,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-0.480000,16.200000,NaN,NaN,NaN,359.000000,1.000000,359.000000,16501.000000,23.5113.5
3,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.100000,17.985000,NaN,NaN,NaN,1161.000000,1.000000,1161.000000,14406.500000,23.5113.5
4,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.100000,15.090000,NaN,NaN,NaN,279.000000,1.000000,279.000000,32002.000000,23.5113.5
5,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,13.700000,NaN,NaN,NaN,822.000000,1.000000,820.000000,10002.000000,23.0113.5
6,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-0.480000,15.050000,NaN,NaN,NaN,2941.000000,0.895000,3390.000000,31902.500000,23.0113.5
7,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,16.170000,NaN,NaN,NaN,677.000000,1.000000,677.000000,27602.000000,23.0113.5
8,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-1.446667,15.310000,NaN,NaN,NaN,1266.333333,1.000000,1266.333333,23102.333333,23.0113.5
9,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-0.480000,14.910000,NaN,NaN,NaN,2111.000000,0.990000,2129.000000,14301.000000,23.0113.5
10,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-1.930000,18.267500,NaN,NaN,NaN,5606.250000,1.000000,5606.250000,2204.500000,23.0113.5
11,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.100000,14.655000,NaN,NaN,NaN,3018.000000,0.995000,3033.500000,1203.500000,23.0113.5
12,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,11.180000,21.355000,NaN,NaN,NaN,2369.500000,1.000000,2369.500000,11907.500000,23.0113.5
13,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,16.370000,NaN,NaN,NaN,525.000000,1.000000,525.000000,16605.000000,23.0113.5
14,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,20.790000,NaN,NaN,NaN,434.000000,1.000000,434.000000,25402.000000,23.0113.5
15,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,11.180000,20.755000,NaN,NaN,NaN,1106.500000,1.000000,1105.000000,24006.000000,23.0113.5
16,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-3.380000,15.920000,NaN,NaN,NaN,3334.000000,1.000000,3334.000000,12108.000000,23.0113.5
17,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,14.570000,NaN,NaN,NaN,5804.000000,0.990000,5840.000000,12202.000000,23.0113.5
18,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,11.180000,17.740000,NaN,NaN,NaN,3136.000000,0.990000,3182.000000,16303.000000,23.0113.5
19,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,16.660000,NaN,NaN,NaN,1000.000000,1.000000,1000.000000,14402.000000,23.0113.5
20,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,11.180000,17.500000,NaN,NaN,NaN,1344.000000,1.000000,1344.000000,36106.000000,23.0113.5
21,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.100000,13.640000,NaN,NaN,NaN,3493.000000,1.000000,3493.000000,25405.000000,23.0113.5
22,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,31.890000,20.275000,NaN,NaN,NaN,3077.500000,0.995000,3087.000000,29303.500000,23.5113.5
23,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.100000,13.430000,NaN,NaN,NaN,1621.000000,1.000000,1621.000000,36402.000000,23.5113.5
24,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,16.830000,NaN,NaN,NaN,1080.500000,1.000000,1081.000000,14406.500000,23.5113.5
25,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,11.180000,20.990000,NaN,NaN,NaN,667.500000,1.000000,667.500000,25107.500000,23.5113.5
26,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,11.180000,21.605000,NaN,NaN,NaN,3395.000000,1.000000,3395.000000,14104.500000,23.5113.5
27,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,14.235000,NaN,NaN,NaN,1561.500000,1.000000,1561.500000,3403.500000,23.5113.5
28,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-0.480000,14.890000,NaN,NaN,NaN,1240.000000,1.000000,1240.000000,14304.000000,23.5113.5
29,45,CHN,China,576,Guangdong,9809,Guangzhou,Guangzhou,???,NaN,...,-12.110000,13.480000,NaN,NaN,NaN,1245.000000,1.000000,1245.000000,32002.000000,23.5113.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,3.910000,17.015000,NaN,NaN,NaN,1648.500000,1.000000,1648.500000,16408.500000,23.5112.5
405,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,5.365000,15.830000,NaN,NaN,NaN,4188.500000,0.970000,4314.000000,15305.000000,23.5112.5
406,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-12.110000,13.535000,NaN,NaN,NaN,3253.000000,0.985000,3351.000000,14406.500000,23.5112.0
407,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-6.280000,15.670000,NaN,NaN,NaN,611.000000,1.000000,611.000000,9903.000000,23.5112.5
408,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,3.907500,21.650000,NaN,NaN,NaN,4566.500000,0.992500,4610.500000,5407.000000,23.5112.5
409,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-8.220000,15.336667,NaN,NaN,NaN,3332.000000,1.000000,3332.000000,15837.000000,23.5112.5
410,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-11.136667,15.090000,NaN,NaN,NaN,857.666667,1.000000,857.666667,10002.666667,23.5112.0
411,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-9.190000,17.700000,NaN,NaN,NaN,4045.500000,0.955000,4202.000000,3405.500000,23.5112.5
412,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,1.483333,17.533333,NaN,NaN,NaN,190.666667,0.996667,191.000000,7636.666667,23.5112.0
413,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,5.360000,21.050000,NaN,NaN,NaN,6010.000000,1.000000,6010.000000,14205.000000,23.5112.5
414,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-11.136667,15.090000,NaN,NaN,NaN,857.666667,1.000000,857.666667,10002.666667,23.5112.0
415,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-6.280000,18.680000,NaN,NaN,NaN,490.000000,1.000000,490.000000,38506.000000,23.5112.5
416,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,12.640000,19.795000,NaN,NaN,NaN,1676.000000,1.000000,1676.000000,18502.500000,23.5112.0
417,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-12.110000,14.860000,NaN,NaN,NaN,7965.000000,1.000000,7965.000000,16602.000000,23.5112.0
418,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-7.735000,14.150000,NaN,NaN,NaN,2820.500000,1.000000,2827.500000,34152.000000,23.5112.5
419,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,2.470000,15.470000,NaN,NaN,NaN,4882.000000,1.000000,4882.000000,16403.000000,23.5112.0
420,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-12.100000,13.390000,NaN,NaN,NaN,1791.000000,1.000000,1791.000000,3402.000000,23.5112.0
421,45,CHN,China,576,Guangdong,9824,Zhaoqing,Zh锟給q锟絥g,???,NaN,...,-3.380000,19.630000,NaN,NaN,NaN,2684.000000,1.000000,2684.000000,27502.000000,23.5111.5
422,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,-0.480000,16.480000,NaN,NaN,NaN,2773.000000,1.000000,2773.000000,7701.000000,22.5113.5
423,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,-0.480000,15.520000,NaN,NaN,NaN,2787.000000,1.000000,2787.000000,20907.000000,22.5113.5
424,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,8.270000,20.380000,NaN,NaN,NaN,185.000000,1.000000,185.000000,23007.000000,22.5113.5
425,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,8.260000,21.630000,NaN,NaN,NaN,4219.000000,1.000000,4223.000000,3204.000000,22.5113.5
426,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,-12.105000,15.910000,NaN,NaN,NaN,689.000000,1.000000,690.000000,16606.500000,22.5113.5
427,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,-1.930000,14.920000,NaN,NaN,NaN,3457.000000,1.000000,3457.000000,30804.500000,22.5113.5
428,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,8.270000,17.360000,NaN,NaN,NaN,2957.000000,0.960000,3065.000000,14207.000000,22.5113.5
429,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,10.216667,16.610000,NaN,NaN,NaN,604.333333,1.006667,600.666667,12673.000000,22.5113.5
430,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,-2.413333,17.086667,70.03,59280.0,14.0,996.666667,1.000000,996.000000,4770.333333,22.5113.5
431,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,-2.413333,18.460000,NaN,NaN,NaN,1359.666667,1.000000,1359.666667,29703.666667,22.5113.5
432,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,-1.930000,16.315000,NaN,NaN,NaN,1160.500000,0.995000,1161.000000,12107.500000,22.5113.5
433,45,CHN,China,576,Guangdong,9825,Zhongshan,Zhongshan,???,NaN,...,-12.110000,15.220000,NaN,NaN,NaN,855.000000,1.000000,855.000000,29805.000000,22.5113.5

In [18]:
df["Date"]=pd.to_datetime(df["BJC"].str.slice(stop=10),format="%Y-%m-%d")

In [19]:
avg_data=df.groupby(['Date']).mean()

In [20]:
avg_data.to_csv("prd_ccn_avg_new.csv")