In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib import cm as CM
from matplotlib.colors import LogNorm,PowerNorm
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.io.shapereader import Reader
import matplotlib.ticker as mticker
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
from shapely.geometry import *
from scipy.interpolate import griddata
import cmocean

In [2]:
fp = "D:/data/map/yrd_grug.shp" #生成的坐标不对
mapfile = gpd.read_file(fp,encoding='gbk')

In [3]:
mapfile

,ID_0,ISO,NAME_0,ID_1,NAME_1,ID_2,NAME_2,VARNAME_2,NL_NAME_2,HASC_2,CC_2,TYPE_2,ENGTYPE_2,VALIDFR_2,VALIDTO_2,REMARKS_2,Shape_Leng,Shape_Area,geometry
0,45,CHN,China,602,Zhejiang,10098,Hangzhou,H锟絥gzhou,???,None,None,1,Prefecture City,Unknown,Present,None,8.960808,1.594394,"(POLYGON ((120.901786 30.23431099999999, 120.9..."
1,45,CHN,China,602,Zhejiang,10099,Huzhou,H锟絲hou,???,None,None,2,Prefecture City,Unknown,Present,None,4.316532,0.546612,"POLYGON ((119.7863470000001 31.17763800000006,..."
2,45,CHN,China,602,Zhejiang,10100,Jiaxing,Jiaxing,???,None,None,2,Prefecture City,Unknown,Present,None,3.842657,0.374464,"(POLYGON ((120.9126350000001 30.365972, 120.91..."
3,45,CHN,China,602,Zhejiang,10101,Jinhua,Jinhu?,???,None,None,2,Prefecture City,Unknown,Present,None,5.796881,1.012312,"POLYGON ((119.8508150000001 29.67336999999998,..."
4,45,CHN,China,602,Zhejiang,10103,Ningbo,N锟絥gbo,???,None,None,2,Prefecture City,Unknown,Present,None,21.595619,0.831543,(POLYGON ((121.8967970000001 29.00681200000002...
5,45,CHN,China,602,Zhejiang,10105,Shaoxing,Sh锟給xing,???,None,None,2,Prefecture City,Unknown,Present,None,4.985468,0.741576,"POLYGON ((120.918939 30.17294700000008, 120.92..."
6,45,CHN,China,602,Zhejiang,10106,Taizhou,Taizhou,???,None,None,2,Prefecture City,Unknown,Present,None,20.525320,0.874436,"(POLYGON ((121.223748 27.93375100000003, 121.2..."
7,45,CHN,China,602,Zhejiang,10108,Zhoushan,Zhoushan,???,None,None,2,Prefecture City,Unknown,Present,None,20.099991,0.115241,(POLYGON ((122.1598600000001 29.61153000000013...
8,45,CHN,China,595,Shanghai,10025,Shanghai,Shanghai,None,None,None,1,Municipality,Unknown,Present,None,14.683208,0.651445,"(POLYGON ((121.702362 30.55958400000014, 121.7..."
9,45,CHN,China,585,Jiangsu,9926,Changzhou,Changzhou,None,None,None,2,Prefecture,Unknown,Present,None,4.948216,0.417194,"POLYGON ((119.852752 32.06026500000007, 119.85..."
10,45,CHN,China,585,Jiangsu,9929,Nanjing,Nanjing,None,None,None,1,Prefecture,Unknown,Present,None,6.164651,0.628212,"POLYGON ((118.7143560000001 32.61158400000011,..."
11,45,CHN,China,585,Jiangsu,9930,Nantong,Nantong,None,None,None,2,Prefecture,Unknown,Present,None,6.354114,0.851394,"POLYGON ((120.383483 32.70652800000005, 120.38..."
12,45,CHN,China,585,Jiangsu,9932,Suzhou,Suzhou,None,None,None,2,Prefecture,Unknown,Present,None,5.796321,0.801724,"POLYGON ((120.565048 32.00230700000003, 120.58..."
13,45,CHN,China,585,Jiangsu,9933,Taizhou,Taizhou,None,None,None,2,Prefecture,Unknown,Present,None,4.997262,0.555351,"POLYGON ((119.749954 33.13395200000014, 119.75..."
14,45,CHN,China,585,Jiangsu,9934,Wuxi,Wuxi,None,None,None,2,Prefecture,Unknown,Present,None,4.754228,0.437079,"POLYGON ((120.3889080000001 31.93353400000012,..."
15,45,CHN,China,585,Jiangsu,9936,Yancheng,Yancheng,None,None,None,2,Prefecture,Unknown,Present,None,10.947030,1.488312,"(POLYGON ((120.924026 32.66013600000008, 120.9..."
16,45,CHN,China,585,Jiangsu,9937,Yangzhou,Yangzhou,None,None,None,2,Prefecture,Unknown,Present,None,4.897332,0.636659,"POLYGON ((119.563676 33.40783600000003, 119.56..."
17,45,CHN,China,585,Jiangsu,9938,Zhenjiang,Zhenjiang,None,None,None,2,Prefecture,Unknown,Present,None,3.941123,0.365249,"POLYGON ((119.847861 32.28412200000002, 119.84..."
18,45,CHN,China,571,Anhui,9764,Anqing,Anqing,None,None,None,2,Prefecture,Unknown,Present,None,6.643409,1.270232,"POLYGON ((117.0228355450245 31.25971749996273,..."
19,45,CHN,China,571,Anhui,9780,Xuancheng,Xuancheng,None,None,None,2,Prefecture,Unknown,Present,None,8.472062,1.159160,"POLYGON ((118.7146177454127 31.3238732947168, ..."
20,45,CHN,China,571,Anhui,9769,Chuzhou,Chuzhou,None,None,None,2,Prefecture,Unknown,Present,None,8.990946,1.297707,"POLYGON ((118.2171079799493 33.14130027009145,..."
21,45,CHN,China,571,Anhui,9776,Maanshan,Waanshan,None,None,None,2,Prefecture,Unknown,Present,None,4.672466,0.386470,"POLYGON ((118.3768961396452 32.03305555037338,..."
22,45,CHN,China,571,Anhui,9779,Wuhu,Wuhu,None,None,None,2,Prefecture,Unknown,Present,None,5.926112,0.567801,"POLYGON ((118.1999249402838 31.52849552544819,..."
23,45,CHN,China,571,Anhui,9768,Chizhou,Chizhou,None,None,None,2,Prefecture,Unknown,Present,None,6.111543,0.787552,"POLYGON ((117.9862261498171 30.82631531480001,..."
24,45,CHN,China,571,Anhui,9778,Tongling,Tongling,None,None,None,2,Prefecture,Unknown,Present,None,3.610885,0.279958,(POLYGON ((116.9693700301028 30.64235563490467...
25,45,CHN,China,571,Anhui,9771,Hefei,Hefei,None,None,None,1,Prefecture,Unknown,Present,None,7.426906,1.087640,"POLYGON ((117.1859819504067 32.53923204462319,..."

In [7]:
data = pd.read_csv('C:/Users/xigrug/Desktop/CCN/avg_CCNnew.csv', sep=',',skiprows=0,header=0)

In [8]:
data

,lat_bin,lon_bin,BJC,AMR_lowest,AMR_surf,AOD,B4LI,CAPE,CAPE_lowest,CAPE_nc,...,satz,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid
0,26.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2121.000000,...,-12.100,14.905000,NaN,NaN,NaN,363.000000,1.000000,363.500000,1203.500000,26.0117.5
1,26.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2048.666667,...,-8.220,15.370000,NaN,NaN,NaN,592.666667,0.996667,594.666667,1170.333333,26.0118.0
2,26.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,-4.830,15.755000,NaN,NaN,NaN,452.500000,1.000000,452.500000,1102.500000,26.0118.5
3,26.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,-0.480,16.260000,NaN,NaN,NaN,171.000000,1.000000,171.000000,1101.000000,26.0119.0
4,26.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2121.000000,...,-12.100,14.930000,NaN,NaN,NaN,1885.000000,1.000000,1885.000000,1208.000000,26.5117.5
5,26.5,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2012.500000,...,-7.735,15.450000,NaN,NaN,NaN,596.500000,1.000000,596.500000,1158.000000,26.5118.0
6,26.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-3.375,15.940000,NaN,NaN,NaN,477.000000,0.980000,491.500000,1106.500000,26.5118.5
7,26.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-0.475,16.280000,NaN,NaN,NaN,584.500000,1.000000,584.500000,1105.500000,26.5119.0
8,27.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,1904.000000,...,-6.280,15.655000,NaN,NaN,NaN,3658.000000,1.000000,3659.000000,3304.500000,27.0118.0
9,27.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-3.380,15.995000,NaN,NaN,NaN,1297.500000,1.000000,1298.500000,3303.500000,27.0118.5
10,27.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-0.480,16.310000,NaN,NaN,NaN,718.000000,1.000000,718.000000,3301.000000,27.0119.0
11,27.0,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.20,812.0,NaN,941.000000,...,28.890,19.910000,NaN,NaN,NaN,1652.000000,1.000000,1652.000000,709.000000,27.0123.0
12,27.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.60,1119.0,NaN,667.000000,...,48.060,23.200000,NaN,NaN,NaN,891.000000,1.010000,880.000000,501.000000,27.0126.5
13,27.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,...,-12.100,15.050000,NaN,NaN,NaN,2395.000000,0.985000,2449.500000,4505.000000,27.5117.0
14,27.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2323.000000,...,-9.190,15.395000,NaN,NaN,NaN,3088.000000,1.170000,2728.000000,4504.000000,27.5117.5
15,27.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1904.000000,...,-0.480,16.355000,NaN,NaN,NaN,2999.000000,0.975000,3064.000000,3305.500000,27.5118.5
16,27.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1631.000000,...,2.470,16.690000,NaN,NaN,NaN,3058.000000,1.000000,3059.500000,3207.500000,27.5119.0
17,27.5,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,28.890,19.930000,NaN,NaN,NaN,788.000000,0.950000,833.000000,2903.000000,27.5123.0
18,27.5,123.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.80,559.0,NaN,749.000000,...,31.900,20.360000,NaN,NaN,NaN,296.000000,1.000000,296.000000,1805.000000,27.5123.5
19,28.0,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,...,-12.100,15.120000,NaN,NaN,NaN,3786.000000,1.000000,3777.000000,5605.000000,28.0117.0
20,28.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2094.500000,...,-7.735,15.630000,NaN,NaN,NaN,5353.000000,1.000000,5353.000000,5555.000000,28.0117.5
21,28.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2081.000000,...,-4.830,15.915000,NaN,NaN,NaN,5609.000000,0.920000,6080.500000,5502.500000,28.0118.0
22,28.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,2081.000000,...,-0.480,16.440000,NaN,NaN,NaN,2661.500000,0.945000,2799.500000,5502.500000,28.0118.5
23,28.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1551.000000,...,2.470,16.750000,NaN,NaN,NaN,411.000000,0.970000,422.000000,5403.000000,28.0119.0
24,28.0,119.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.90,1670.0,NaN,1551.000000,...,8.270,17.410000,NaN,NaN,NaN,827.000000,1.000000,827.000000,5401.000000,28.0119.5
25,28.0,122.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,28.890,19.980000,NaN,NaN,NaN,1010.000000,0.720000,1405.000000,2909.000000,28.0122.5
26,28.0,125.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,43.760,22.390000,NaN,NaN,NaN,4333.000000,0.870000,4990.000000,2706.000000,28.0125.5
27,28.0,126.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,45.900,22.810000,NaN,NaN,NaN,3949.000000,0.910000,4326.000000,2705.000000,28.0126.0
28,28.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.90,515.0,NaN,667.000000,...,48.060,23.250000,NaN,NaN,NaN,2808.500000,0.960000,2949.000000,2702.500000,28.0126.5
29,28.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-2.10,752.0,NaN,1621.666667,...,-10.160,15.426667,NaN,NaN,NaN,6812.000000,1.000000,6812.000000,6338.666667,28.5117.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76906,35.0,123.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2033.0,NaN,1075.000000,...,2.460,29.740000,NaN,NaN,NaN,845.000000,1.000000,845.000000,42803.000000,35.0123.5
76907,35.0,124.0,2018-08-30 04:42:00,NaN,NaN,NaN,-5.40,2061.0,NaN,1075.000000,...,5.360,29.970000,NaN,NaN,NaN,675.000000,1.000000,675.000000,42802.000000,35.0124.0
76908,35.0,124.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.80,1686.0,NaN,1242.000000,...,11.180,30.440000,NaN,NaN,NaN,1112.000000,1.000000,1112.000000,42703.000000,35.0124.5
76909,35.0,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.65,1711.5,NaN,1276.000000,...,14.100,30.565000,NaN,NaN,NaN,2437.000000,1.000000,2437.000000,41605.000000,35.0125.0
76910,35.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1320.0,NaN,1864.000000,...,22.930,31.240000,NaN,NaN,NaN,1782.000000,1.000000,1782.000000,40408.000000,35.0126.5
76911,35.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.60,1222.0,NaN,1373.000000,...,34.940,32.280000,NaN,NaN,NaN,78.000000,1.000000,78.000000,40304.000000,35.0128.5
76912,35.5,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.20,1377.0,NaN,1170.000000,...,-12.110,29.370000,NaN,NaN,NaN,661.000000,1.000000,661.000000,45202.000000,35.5121.0
76913,35.5,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1425.0,NaN,1242.000000,...,14.100,30.910000,NaN,NaN,NaN,2670.000000,1.000000,2670.000000,42705.000000,35.5125.0
76914,35.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1221.0,NaN,1408.000000,...,22.920,31.460000,NaN,NaN,NaN,3193.000000,1.000000,3193.000000,42602.000000,35.5126.5
76915,35.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.25,1838.0,NaN,1629.500000,...,34.940,32.595000,NaN,NaN,NaN,3678.000000,1.000000,3683.000000,41404.000000,35.5128.5
76916,35.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.60,1750.0,NaN,1594.000000,...,37.500,33.010000,NaN,NaN,NaN,556.000000,1.000000,557.000000,42403.000000,35.5129.0
76917,36.0,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,517.5,NaN,1170.000000,...,-12.110,29.735000,NaN,NaN,NaN,1930.000000,0.960000,1943.000000,45206.500000,36.0121.0
76918,36.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.40,1316.0,NaN,1408.000000,...,25.900,32.190000,NaN,NaN,NaN,4450.000000,0.970000,4571.000000,42607.000000,36.0127.0
76919,36.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.15,1333.5,NaN,1886.000000,...,28.885,32.370000,NaN,NaN,NaN,2245.500000,0.940000,2421.000000,42507.500000,36.0127.5
76920,36.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1779.0,NaN,1886.000000,...,31.900,32.690000,NaN,NaN,NaN,3705.500000,1.000000,3709.500000,42506.500000,36.0128.0
76921,36.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1754.0,NaN,1886.000000,...,34.940,32.920000,NaN,NaN,NaN,4548.000000,1.000000,4548.000000,42504.000000,36.0128.5
76922,36.5,121.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.75,300.5,NaN,1142.500000,...,-7.745,30.180000,NaN,NaN,NaN,2487.500000,0.995000,2494.000000,45158.000000,36.5121.5
76923,36.5,122.0,2018-08-30 04:42:00,NaN,NaN,NaN,-1.70,0.0,NaN,1115.000000,...,-3.380,30.500000,NaN,NaN,NaN,730.000000,1.000000,730.000000,45108.000000,36.5122.0
76924,36.5,122.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.80,0.0,NaN,1115.000000,...,-0.480,30.710000,NaN,NaN,NaN,747.000000,1.000000,747.000000,45107.000000,36.5122.5
76925,36.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1328.5,NaN,246.000000,...,25.900,32.525000,NaN,NaN,NaN,1799.500000,1.000000,1799.000000,44802.500000,36.5126.5
76926,36.5,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1485.0,NaN,1437.000000,...,28.890,32.710000,NaN,NaN,NaN,4552.000000,0.980000,4644.000000,44703.000000,36.5127.0
76927,36.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1536.0,NaN,1886.000000,...,34.940,33.140000,NaN,NaN,NaN,2820.000000,0.980000,2879.000000,42507.000000,36.5128.5
76928,36.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.00,1457.0,NaN,1314.000000,...,37.490,33.650000,NaN,NaN,NaN,1772.000000,1.000000,1776.000000,44603.000000,36.5129.0
76929,36.5,129.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2236.0,NaN,1594.000000,...,39.560,33.700000,NaN,NaN,NaN,563.000000,0.920000,613.000000,42408.000000,36.5129.5
76930,37.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,192.0,NaN,246.000000,...,25.900,32.870000,NaN,NaN,NaN,4359.000000,0.990000,4399.000000,44807.000000,37.0126.5
76931,37.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1302.5,NaN,1437.000000,...,28.890,33.040000,NaN,NaN,NaN,4474.500000,0.935000,4724.500000,44707.500000,37.0127.0
76932,37.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1567.5,NaN,1437.000000,...,31.900,33.350000,NaN,NaN,NaN,4152.000000,0.925000,4449.000000,44706.500000,37.0127.5
76933,37.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,781.0,NaN,1437.000000,...,34.940,33.790000,NaN,NaN,NaN,7740.000000,1.000000,7740.000000,44707.000000,37.0128.0
76934,37.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,825.0,NaN,1437.000000,...,34.940,33.570000,NaN,NaN,NaN,5428.000000,1.000000,5428.000000,44704.000000,37.0128.5
76935,37.0,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.80,1380.0,NaN,1314.000000,...,37.490,33.870000,NaN,NaN,NaN,3439.000000,1.000000,3456.000000,44606.000000,37.0129.0

In [9]:
data['Coordinates'] = list(zip(data.lon_bin, data.lat_bin))
data['Coordinates'] = data['Coordinates'].apply(Point)

In [10]:
# get geo data
gdf = gpd.GeoDataFrame(data, geometry='Coordinates')
gdf.crs = mapfile.crs
#gdf=gdf.dropna(subset=[ '2001'])#Remember to reassign
cities_with_country = gpd.sjoin(mapfile,gdf,how="inner", op='intersects')
#print(df1)
#df1.to_csv("cities_with_country.csv")

In [11]:
gdf

,lat_bin,lon_bin,BJC,AMR_lowest,AMR_surf,AOD,B4LI,CAPE,CAPE_lowest,CAPE_nc,...,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid,Coordinates
0,26.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2121.000000,...,14.905000,NaN,NaN,NaN,363.000000,1.000000,363.500000,1203.500000,26.0117.5,POINT (117.5 26)
1,26.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2048.666667,...,15.370000,NaN,NaN,NaN,592.666667,0.996667,594.666667,1170.333333,26.0118.0,POINT (118 26)
2,26.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,15.755000,NaN,NaN,NaN,452.500000,1.000000,452.500000,1102.500000,26.0118.5,POINT (118.5 26)
3,26.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,16.260000,NaN,NaN,NaN,171.000000,1.000000,171.000000,1101.000000,26.0119.0,POINT (119 26)
4,26.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2121.000000,...,14.930000,NaN,NaN,NaN,1885.000000,1.000000,1885.000000,1208.000000,26.5117.5,POINT (117.5 26.5)
5,26.5,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2012.500000,...,15.450000,NaN,NaN,NaN,596.500000,1.000000,596.500000,1158.000000,26.5118.0,POINT (118 26.5)
6,26.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,15.940000,NaN,NaN,NaN,477.000000,0.980000,491.500000,1106.500000,26.5118.5,POINT (118.5 26.5)
7,26.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,16.280000,NaN,NaN,NaN,584.500000,1.000000,584.500000,1105.500000,26.5119.0,POINT (119 26.5)
8,27.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,1904.000000,...,15.655000,NaN,NaN,NaN,3658.000000,1.000000,3659.000000,3304.500000,27.0118.0,POINT (118 27)
9,27.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,15.995000,NaN,NaN,NaN,1297.500000,1.000000,1298.500000,3303.500000,27.0118.5,POINT (118.5 27)
10,27.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,16.310000,NaN,NaN,NaN,718.000000,1.000000,718.000000,3301.000000,27.0119.0,POINT (119 27)
11,27.0,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.20,812.0,NaN,941.000000,...,19.910000,NaN,NaN,NaN,1652.000000,1.000000,1652.000000,709.000000,27.0123.0,POINT (123 27)
12,27.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.60,1119.0,NaN,667.000000,...,23.200000,NaN,NaN,NaN,891.000000,1.010000,880.000000,501.000000,27.0126.5,POINT (126.5 27)
13,27.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,...,15.050000,NaN,NaN,NaN,2395.000000,0.985000,2449.500000,4505.000000,27.5117.0,POINT (117 27.5)
14,27.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2323.000000,...,15.395000,NaN,NaN,NaN,3088.000000,1.170000,2728.000000,4504.000000,27.5117.5,POINT (117.5 27.5)
15,27.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1904.000000,...,16.355000,NaN,NaN,NaN,2999.000000,0.975000,3064.000000,3305.500000,27.5118.5,POINT (118.5 27.5)
16,27.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1631.000000,...,16.690000,NaN,NaN,NaN,3058.000000,1.000000,3059.500000,3207.500000,27.5119.0,POINT (119 27.5)
17,27.5,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,19.930000,NaN,NaN,NaN,788.000000,0.950000,833.000000,2903.000000,27.5123.0,POINT (123 27.5)
18,27.5,123.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.80,559.0,NaN,749.000000,...,20.360000,NaN,NaN,NaN,296.000000,1.000000,296.000000,1805.000000,27.5123.5,POINT (123.5 27.5)
19,28.0,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,...,15.120000,NaN,NaN,NaN,3786.000000,1.000000,3777.000000,5605.000000,28.0117.0,POINT (117 28)
20,28.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2094.500000,...,15.630000,NaN,NaN,NaN,5353.000000,1.000000,5353.000000,5555.000000,28.0117.5,POINT (117.5 28)
21,28.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2081.000000,...,15.915000,NaN,NaN,NaN,5609.000000,0.920000,6080.500000,5502.500000,28.0118.0,POINT (118 28)
22,28.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,2081.000000,...,16.440000,NaN,NaN,NaN,2661.500000,0.945000,2799.500000,5502.500000,28.0118.5,POINT (118.5 28)
23,28.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1551.000000,...,16.750000,NaN,NaN,NaN,411.000000,0.970000,422.000000,5403.000000,28.0119.0,POINT (119 28)
24,28.0,119.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.90,1670.0,NaN,1551.000000,...,17.410000,NaN,NaN,NaN,827.000000,1.000000,827.000000,5401.000000,28.0119.5,POINT (119.5 28)
25,28.0,122.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,19.980000,NaN,NaN,NaN,1010.000000,0.720000,1405.000000,2909.000000,28.0122.5,POINT (122.5 28)
26,28.0,125.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,22.390000,NaN,NaN,NaN,4333.000000,0.870000,4990.000000,2706.000000,28.0125.5,POINT (125.5 28)
27,28.0,126.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,22.810000,NaN,NaN,NaN,3949.000000,0.910000,4326.000000,2705.000000,28.0126.0,POINT (126 28)
28,28.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.90,515.0,NaN,667.000000,...,23.250000,NaN,NaN,NaN,2808.500000,0.960000,2949.000000,2702.500000,28.0126.5,POINT (126.5 28)
29,28.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-2.10,752.0,NaN,1621.666667,...,15.426667,NaN,NaN,NaN,6812.000000,1.000000,6812.000000,6338.666667,28.5117.0,POINT (117 28.5)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76906,35.0,123.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2033.0,NaN,1075.000000,...,29.740000,NaN,NaN,NaN,845.000000,1.000000,845.000000,42803.000000,35.0123.5,POINT (123.5 35)
76907,35.0,124.0,2018-08-30 04:42:00,NaN,NaN,NaN,-5.40,2061.0,NaN,1075.000000,...,29.970000,NaN,NaN,NaN,675.000000,1.000000,675.000000,42802.000000,35.0124.0,POINT (124 35)
76908,35.0,124.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.80,1686.0,NaN,1242.000000,...,30.440000,NaN,NaN,NaN,1112.000000,1.000000,1112.000000,42703.000000,35.0124.5,POINT (124.5 35)
76909,35.0,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.65,1711.5,NaN,1276.000000,...,30.565000,NaN,NaN,NaN,2437.000000,1.000000,2437.000000,41605.000000,35.0125.0,POINT (125 35)
76910,35.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1320.0,NaN,1864.000000,...,31.240000,NaN,NaN,NaN,1782.000000,1.000000,1782.000000,40408.000000,35.0126.5,POINT (126.5 35)
76911,35.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.60,1222.0,NaN,1373.000000,...,32.280000,NaN,NaN,NaN,78.000000,1.000000,78.000000,40304.000000,35.0128.5,POINT (128.5 35)
76912,35.5,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.20,1377.0,NaN,1170.000000,...,29.370000,NaN,NaN,NaN,661.000000,1.000000,661.000000,45202.000000,35.5121.0,POINT (121 35.5)
76913,35.5,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1425.0,NaN,1242.000000,...,30.910000,NaN,NaN,NaN,2670.000000,1.000000,2670.000000,42705.000000,35.5125.0,POINT (125 35.5)
76914,35.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1221.0,NaN,1408.000000,...,31.460000,NaN,NaN,NaN,3193.000000,1.000000,3193.000000,42602.000000,35.5126.5,POINT (126.5 35.5)
76915,35.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.25,1838.0,NaN,1629.500000,...,32.595000,NaN,NaN,NaN,3678.000000,1.000000,3683.000000,41404.000000,35.5128.5,POINT (128.5 35.5)
76916,35.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.60,1750.0,NaN,1594.000000,...,33.010000,NaN,NaN,NaN,556.000000,1.000000,557.000000,42403.000000,35.5129.0,POINT (129 35.5)
76917,36.0,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,517.5,NaN,1170.000000,...,29.735000,NaN,NaN,NaN,1930.000000,0.960000,1943.000000,45206.500000,36.0121.0,POINT (121 36)
76918,36.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.40,1316.0,NaN,1408.000000,...,32.190000,NaN,NaN,NaN,4450.000000,0.970000,4571.000000,42607.000000,36.0127.0,POINT (127 36)
76919,36.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.15,1333.5,NaN,1886.000000,...,32.370000,NaN,NaN,NaN,2245.500000,0.940000,2421.000000,42507.500000,36.0127.5,POINT (127.5 36)
76920,36.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1779.0,NaN,1886.000000,...,32.690000,NaN,NaN,NaN,3705.500000,1.000000,3709.500000,42506.500000,36.0128.0,POINT (128 36)
76921,36.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1754.0,NaN,1886.000000,...,32.920000,NaN,NaN,NaN,4548.000000,1.000000,4548.000000,42504.000000,36.0128.5,POINT (128.5 36)
76922,36.5,121.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.75,300.5,NaN,1142.500000,...,30.180000,NaN,NaN,NaN,2487.500000,0.995000,2494.000000,45158.000000,36.5121.5,POINT (121.5 36.5)
76923,36.5,122.0,2018-08-30 04:42:00,NaN,NaN,NaN,-1.70,0.0,NaN,1115.000000,...,30.500000,NaN,NaN,NaN,730.000000,1.000000,730.000000,45108.000000,36.5122.0,POINT (122 36.5)
76924,36.5,122.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.80,0.0,NaN,1115.000000,...,30.710000,NaN,NaN,NaN,747.000000,1.000000,747.000000,45107.000000,36.5122.5,POINT (122.5 36.5)
76925,36.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1328.5,NaN,246.000000,...,32.525000,NaN,NaN,NaN,1799.500000,1.000000,1799.000000,44802.500000,36.5126.5,POINT (126.5 36.5)
76926,36.5,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1485.0,NaN,1437.000000,...,32.710000,NaN,NaN,NaN,4552.000000,0.980000,4644.000000,44703.000000,36.5127.0,POINT (127 36.5)
76927,36.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1536.0,NaN,1886.000000,...,33.140000,NaN,NaN,NaN,2820.000000,0.980000,2879.000000,42507.000000,36.5128.5,POINT (128.5 36.5)
76928,36.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.00,1457.0,NaN,1314.000000,...,33.650000,NaN,NaN,NaN,1772.000000,1.000000,1776.000000,44603.000000,36.5129.0,POINT (129 36.5)
76929,36.5,129.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2236.0,NaN,1594.000000,...,33.700000,NaN,NaN,NaN,563.000000,0.920000,613.000000,42408.000000,36.5129.5,POINT (129.5 36.5)
76930,37.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,192.0,NaN,246.000000,...,32.870000,NaN,NaN,NaN,4359.000000,0.990000,4399.000000,44807.000000,37.0126.5,POINT (126.5 37)
76931,37.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1302.5,NaN,1437.000000,...,33.040000,NaN,NaN,NaN,4474.500000,0.935000,4724.500000,44707.500000,37.0127.0,POINT (127 37)
76932,37.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1567.5,NaN,1437.000000,...,33.350000,NaN,NaN,NaN,4152.000000,0.925000,4449.000000,44706.500000,37.0127.5,POINT (127.5 37)
76933,37.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,781.0,NaN,1437.000000,...,33.790000,NaN,NaN,NaN,7740.000000,1.000000,7740.000000,44707.000000,37.0128.0,POINT (128 37)
76934,37.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,825.0,NaN,1437.000000,...,33.570000,NaN,NaN,NaN,5428.000000,1.000000,5428.000000,44704.000000,37.0128.5,POINT (128.5 37)
76935,37.0,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.80,1380.0,NaN,1314.000000,...,33.870000,NaN,NaN,NaN,3439.000000,1.000000,3456.000000,44606.000000,37.0129.0,POINT (129 37)

In [12]:
cities_with_country = gpd.sjoin(mapfile,gdf,how="inner", op='intersects')

In [13]:
cities_with_country=cities_with_country.drop(["geometry"],axis=1)

In [20]:
cities_with_country.to_csv("yrd_ccn_new.csv")

In [21]:
df=pd.read_csv("yrd_ccn_new.csv")

In [22]:
df=df.drop(["Unnamed: 0"],axis=1)

In [23]:
df["Date"]=pd.to_datetime(df["BJC"].str.slice(stop=10),format="%Y-%m-%d")

In [24]:
avg_data=df.groupby(['Date']).mean()

In [25]:
avg_data.to_csv("yrd_ccn_avg_new.csv")