In [1]:
import pygrib
import pandas as pd
import numpy as np

Read data

In [2]:
file = '/data/c02n03/archive/ds083.3/2015/gdas1.fnl0p25.2015081106.f00.grib2' #example filename
gr = pygrib.open(file)

In [3]:
df = pd.read_csv("../201508/AUTO_5MINS_NPP_MicroPhys_20150811_0455_Table.txt", sep='\s+',skiprows=0,header=0,na_values=[-99,-9999])

In [4]:
def find_nearest(array,value):
    idx = (np.abs(array-value)).argmin()
    return array[idx]

In [5]:
def potential_temperature(T,p):
    """Compute potential temperature for an air parcel.

    Input:  T is temperature in Kelvin
            p is pressure in mb or hPa
    Output: potential temperature in Kelvin.

    """
    ps=1000
    cp = 1004.     # specific heat at constant pressure for dry air (J / kg / K)
    Rd = 287.         # gas constant for dry air (J / kg / K)
    kappa = Rd/cp
    theta = T*(ps/p)**kappa
    return theta

In [6]:
#pblh=gr.select(name='Planetary boundary layer height')
#pblh
#pblh=pblh.values

In [7]:
pblh=gr.select(name='Planetary boundary layer height')[0]
pblhv=pblh.values
print(pblhv.shape)
print(np.amax(pblhv),np.amin(pblhv))

(721, 1440)
3966.0398 17.0

In [8]:
#get record number
ptems = gr[299] #Potential temperature
ptemsv=ptems.values
T1000= gr[208]
T1000v=T1000.values
Tsurf = gr[219]
Tsurfv=Tsurf.values
T500= gr[112]
T500v=T500.values
T850= gr[168]
T850v=T850.values
T700= gr[144]
T700v=T700.values
Gh1000= gr[216]
Gh1000v=Gh1000.values
Gh500= gr[111]
Gh500v=Gh500.values
Gh850= gr[167]
Gh850v=Gh850.values
Gh700= gr[143]
Gh700v=Gh700.values
ST0 = gr[220]
ST0v=ST0.values
Sli = gr.select(name='Surface lifted index')[0]
Sliv=Sli.values
B4li = gr.select(name='Best (4-layer) lifted index')[0]
B4liv=B4li.values
LSM = gr.select(name='Land-sea mask')[0]
LSMv=LSM.values
Tozone = gr.select(name='Total ozone')[0]
Tozonev=Tozone.values
Srh = gr.select(name='Storm relative helicity')[0]
Srhv=Srh.values
Cape = gr.select(name='Convective available potential energy')[0]
Capev=Cape.values
Pr = gr.select(name='Cloud water')[0]
Prv= Pr.values
Pw = gr.select(name='Precipitable water')[0]
Pwv=Pw.values
CIN0 = gr[243]
CIN0v =CIN0.values
CIN180 = gr[292]
CIN180v=CIN180.values
CIN255 = gr[305]
CIN255v=CIN255.values
Sh2 =gr [231]#Specific humidity 2m
Sh2v=Sh2.values
TD2 = gr.select(name='2 metre dewpoint temperature')[0]
TD2v=TD2.values
RH2 = gr.select(name='2 metre relative humidity')[0]
RH2v= RH2.values

In [9]:
ptem700v= potential_temperature(T700v, 700)
print(np.amax(ptem700v),np.amin(ptem700v))

331.86887 239.07404

In [10]:
lts= ptem700v-ptemsv

In [11]:
lts

array([[17.694    , 17.694    , 17.694    , ..., 17.694    , 17.694    ,
        17.694    ],
       [17.704742 , 17.704742 , 17.704742 , ..., 17.704742 , 17.704742 ,
        17.704742 ],
       [17.826202 , 17.826202 , 17.826202 , ..., 17.826202 , 17.826202 ,
        17.826202 ],
       ...,
       [-1.1672668, -1.1672668, -1.1672668, ..., -1.1672668, -1.1672668,
        -1.1672668],
       [-1.2350769, -1.1243286, -1.1243286, ..., -1.2350769, -1.2350769,
        -1.2350769],
       [-1.2350769, -1.2350769, -1.2350769, ..., -1.2350769, -1.2350769,
        -1.2350769]], dtype=float32)

In [12]:
print(lts.shape)
print(np.amax(lts),np.amin(lts))

(721, 1440)
37.706512 -12.907898

In [13]:
lat,lon=df["lat"],df["lon"]

In [14]:
lat,lon

(0       37.3944
 1       37.7066
 2       37.6469
 3       38.0790
 4       38.0190
 5       37.9589
 6       37.2766
 7       37.2183
 8       37.1595
 9       37.5887
 10      37.5302
 11      37.4709
 12      37.9006
 13      37.8419
 14      37.7827
 15      37.0978
 16      37.0378
 17      36.9768
 18      37.4093
 19      37.3490
 20      37.2878
 21      37.7207
 22      37.5986
 23      36.9146
 24      36.8511
 25      36.7857
 26      37.2254
 27      37.1616
 28      37.0959
 29      37.5360
          ...
 3027    19.3975
 3028    23.6883
 3029    24.0741
 3030    23.9987
 3031    24.3838
 3032    24.3462
 3033    24.3093
 3034    23.6522
 3035    23.6172
 3036    23.5836
 3037    23.9630
 3038    23.9282
 3039    23.8618
 3040    23.8298
 3041    23.7997
 3042    23.3678
 3043    23.7685
 3044    23.9930
 3045    23.8880
 3046    23.1659
 3047    23.1193
 3048    23.4326
 3049    23.3892
 3050    23.7924
 3051    23.7459
 3052    23.7027
 3053    23.3353
 3054    23.2746
 3055    23.6488
 3056    23.5881
 Name: lat, Length: 3057, dtype: float64, 0       124.6297
 1       124.5471
 2       124.0689
 3       124.9651
 4       124.4641
 5       123.9830
 6       123.6943
 7       123.2483
 8       122.8148
 9       123.6069
 10      123.1595
 11      122.7235
 12      123.5197
 13      123.0707
 14      122.6324
 15      122.3892
 16      121.9705
 17      121.5565
 18      122.2972
 19      121.8767
 20      121.4605
 21      122.2046
 22      121.3643
 23      121.1439
 24      120.7323
 25      120.3195
 26      121.0467
 27      120.6336
 28      120.2185
 29      120.9493
           ...
 3027    116.4931
 3028    141.5398
 3029    142.5208
 3030    141.4893
 3031    142.4744
 3032    141.9363
 3033    141.4402
 3034    141.0798
 3035    140.6501
 3036    140.2463
 3037    141.0294
 3038    140.5978
 3039    139.8125
 3040    139.4529
 3041    139.1115
 3042    137.9144
 3043    138.7861
 3044    137.7960
 3045    136.7779
 3046    136.0199
 3047    135.6200
 3048    135.5557
 3049    135.1747
 3050    135.8921
 3051    135.4903
 3052    135.1088
 3053    134.7272
 3054    134.2207
 3055    134.6596
 3056    134.1529
 Name: lon, Length: 3057, dtype: float64)

In [15]:
lon_list,lat_list = ptems.latlons()[1][0],ptems.latlons()[0].T[0]

In [16]:
lon_list,lat_list

(array([0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5925e+02, 3.5950e+02,
        3.5975e+02]),
 array([ 90.  ,  89.75,  89.5 ,  89.25,  89.  ,  88.75,  88.5 ,  88.25,
         88.  ,  87.75,  87.5 ,  87.25,  87.  ,  86.75,  86.5 ,  86.25,
         86.  ,  85.75,  85.5 ,  85.25,  85.  ,  84.75,  84.5 ,  84.25,
         84.  ,  83.75,  83.5 ,  83.25,  83.  ,  82.75,  82.5 ,  82.25,
         82.  ,  81.75,  81.5 ,  81.25,  81.  ,  80.75,  80.5 ,  80.25,
         80.  ,  79.75,  79.5 ,  79.25,  79.  ,  78.75,  78.5 ,  78.25,
         78.  ,  77.75,  77.5 ,  77.25,  77.  ,  76.75,  76.5 ,  76.25,
         76.  ,  75.75,  75.5 ,  75.25,  75.  ,  74.75,  74.5 ,  74.25,
         74.  ,  73.75,  73.5 ,  73.25,  73.  ,  72.75,  72.5 ,  72.25,
         72.  ,  71.75,  71.5 ,  71.25,  71.  ,  70.75,  70.5 ,  70.25,
         70.  ,  69.75,  69.5 ,  69.25,  69.  ,  68.75,  68.5 ,  68.25,
         68.  ,  67.75,  67.5 ,  67.25,  67.  ,  66.75,  66.5 ,  66.25,
         66.  ,  65.75,  65.5 ,  65.25,  65.  ,  64.75,  64.5 ,  64.25,
         64.  ,  63.75,  63.5 ,  63.25,  63.  ,  62.75,  62.5 ,  62.25,
         62.  ,  61.75,  61.5 ,  61.25,  61.  ,  60.75,  60.5 ,  60.25,
         60.  ,  59.75,  59.5 ,  59.25,  59.  ,  58.75,  58.5 ,  58.25,
         58.  ,  57.75,  57.5 ,  57.25,  57.  ,  56.75,  56.5 ,  56.25,
         56.  ,  55.75,  55.5 ,  55.25,  55.  ,  54.75,  54.5 ,  54.25,
         54.  ,  53.75,  53.5 ,  53.25,  53.  ,  52.75,  52.5 ,  52.25,
         52.  ,  51.75,  51.5 ,  51.25,  51.  ,  50.75,  50.5 ,  50.25,
         50.  ,  49.75,  49.5 ,  49.25,  49.  ,  48.75,  48.5 ,  48.25,
         48.  ,  47.75,  47.5 ,  47.25,  47.  ,  46.75,  46.5 ,  46.25,
         46.  ,  45.75,  45.5 ,  45.25,  45.  ,  44.75,  44.5 ,  44.25,
         44.  ,  43.75,  43.5 ,  43.25,  43.  ,  42.75,  42.5 ,  42.25,
         42.  ,  41.75,  41.5 ,  41.25,  41.  ,  40.75,  40.5 ,  40.25,
         40.  ,  39.75,  39.5 ,  39.25,  39.  ,  38.75,  38.5 ,  38.25,
         38.  ,  37.75,  37.5 ,  37.25,  37.  ,  36.75,  36.5 ,  36.25,
         36.  ,  35.75,  35.5 ,  35.25,  35.  ,  34.75,  34.5 ,  34.25,
         34.  ,  33.75,  33.5 ,  33.25,  33.  ,  32.75,  32.5 ,  32.25,
         32.  ,  31.75,  31.5 ,  31.25,  31.  ,  30.75,  30.5 ,  30.25,
         30.  ,  29.75,  29.5 ,  29.25,  29.  ,  28.75,  28.5 ,  28.25,
         28.  ,  27.75,  27.5 ,  27.25,  27.  ,  26.75,  26.5 ,  26.25,
         26.  ,  25.75,  25.5 ,  25.25,  25.  ,  24.75,  24.5 ,  24.25,
         24.  ,  23.75,  23.5 ,  23.25,  23.  ,  22.75,  22.5 ,  22.25,
         22.  ,  21.75,  21.5 ,  21.25,  21.  ,  20.75,  20.5 ,  20.25,
         20.  ,  19.75,  19.5 ,  19.25,  19.  ,  18.75,  18.5 ,  18.25,
         18.  ,  17.75,  17.5 ,  17.25,  17.  ,  16.75,  16.5 ,  16.25,
         16.  ,  15.75,  15.5 ,  15.25,  15.  ,  14.75,  14.5 ,  14.25,
         14.  ,  13.75,  13.5 ,  13.25,  13.  ,  12.75,  12.5 ,  12.25,
         12.  ,  11.75,  11.5 ,  11.25,  11.  ,  10.75,  10.5 ,  10.25,
         10.  ,   9.75,   9.5 ,   9.25,   9.  ,   8.75,   8.5 ,   8.25,
          8.  ,   7.75,   7.5 ,   7.25,   7.  ,   6.75,   6.5 ,   6.25,
          6.  ,   5.75,   5.5 ,   5.25,   5.  ,   4.75,   4.5 ,   4.25,
          4.  ,   3.75,   3.5 ,   3.25,   3.  ,   2.75,   2.5 ,   2.25,
          2.  ,   1.75,   1.5 ,   1.25,   1.  ,   0.75,   0.5 ,   0.25,
          0.  ,  -0.25,  -0.5 ,  -0.75,  -1.  ,  -1.25,  -1.5 ,  -1.75,
         -2.  ,  -2.25,  -2.5 ,  -2.75,  -3.  ,  -3.25,  -3.5 ,  -3.75,
         -4.  ,  -4.25,  -4.5 ,  -4.75,  -5.  ,  -5.25,  -5.5 ,  -5.75,
         -6.  ,  -6.25,  -6.5 ,  -6.75,  -7.  ,  -7.25,  -7.5 ,  -7.75,
         -8.  ,  -8.25,  -8.5 ,  -8.75,  -9.  ,  -9.25,  -9.5 ,  -9.75,
        -10.  , -10.25, -10.5 , -10.75, -11.  , -11.25, -11.5 , -11.75,
        -12.  , -12.25, -12.5 , -12.75, -13.  , -13.25, -13.5 , -13.75,
        -14.  , -14.25, -14.5 , -14.75, -15.  , -15.25, -15.5 , -15.75,
        -16.  , -16.25, -16.5 , -16.75, -17.  , -17.25, -17.5 , -17.75,
        -18.  , -18.25, -18.5 , -18.75, -19.  , -19.25, -19.5 , -19.75,
        -20.  , -20.25, -20.5 , -20.75, -21.  , -21.25, -21.5 , -21.75,
        -22.  , -22.25, -22.5 , -22.75, -23.  , -23.25, -23.5 , -23.75,
        -24.  , -24.25, -24.5 , -24.75, -25.  , -25.25, -25.5 , -25.75,
        -26.  , -26.25, -26.5 , -26.75, -27.  , -27.25, -27.5 , -27.75,
        -28.  , -28.25, -28.5 , -28.75, -29.  , -29.25, -29.5 , -29.75,
        -30.  , -30.25, -30.5 , -30.75, -31.  , -31.25, -31.5 , -31.75,
        -32.  , -32.25, -32.5 , -32.75, -33.  , -33.25, -33.5 , -33.75,
        -34.  , -34.25, -34.5 , -34.75, -35.  , -35.25, -35.5 , -35.75,
        -36.  , -36.25, -36.5 , -36.75, -37.  , -37.25, -37.5 , -37.75,
        -38.  , -38.25, -38.5 , -38.75, -39.  , -39.25, -39.5 , -39.75,
        -40.  , -40.25, -40.5 , -40.75, -41.  , -41.25, -41.5 , -41.75,
        -42.  , -42.25, -42.5 , -42.75, -43.  , -43.25, -43.5 , -43.75,
        -44.  , -44.25, -44.5 , -44.75, -45.  , -45.25, -45.5 , -45.75,
        -46.  , -46.25, -46.5 , -46.75, -47.  , -47.25, -47.5 , -47.75,
        -48.  , -48.25, -48.5 , -48.75, -49.  , -49.25, -49.5 , -49.75,
        -50.  , -50.25, -50.5 , -50.75, -51.  , -51.25, -51.5 , -51.75,
        -52.  , -52.25, -52.5 , -52.75, -53.  , -53.25, -53.5 , -53.75,
        -54.  , -54.25, -54.5 , -54.75, -55.  , -55.25, -55.5 , -55.75,
        -56.  , -56.25, -56.5 , -56.75, -57.  , -57.25, -57.5 , -57.75,
        -58.  , -58.25, -58.5 , -58.75, -59.  , -59.25, -59.5 , -59.75,
        -60.  , -60.25, -60.5 , -60.75, -61.  , -61.25, -61.5 , -61.75,
        -62.  , -62.25, -62.5 , -62.75, -63.  , -63.25, -63.5 , -63.75,
        -64.  , -64.25, -64.5 , -64.75, -65.  , -65.25, -65.5 , -65.75,
        -66.  , -66.25, -66.5 , -66.75, -67.  , -67.25, -67.5 , -67.75,
        -68.  , -68.25, -68.5 , -68.75, -69.  , -69.25, -69.5 , -69.75,
        -70.  , -70.25, -70.5 , -70.75, -71.  , -71.25, -71.5 , -71.75,
        -72.  , -72.25, -72.5 , -72.75, -73.  , -73.25, -73.5 , -73.75,
        -74.  , -74.25, -74.5 , -74.75, -75.  , -75.25, -75.5 , -75.75,
        -76.  , -76.25, -76.5 , -76.75, -77.  , -77.25, -77.5 , -77.75,
        -78.  , -78.25, -78.5 , -78.75, -79.  , -79.25, -79.5 , -79.75,
        -80.  , -80.25, -80.5 , -80.75, -81.  , -81.25, -81.5 , -81.75,
        -82.  , -82.25, -82.5 , -82.75, -83.  , -83.25, -83.5 , -83.75,
        -84.  , -84.25, -84.5 , -84.75, -85.  , -85.25, -85.5 , -85.75,
        -86.  , -86.25, -86.5 , -86.75, -87.  , -87.25, -87.5 , -87.75,
        -88.  , -88.25, -88.5 , -88.75, -89.  , -89.25, -89.5 , -89.75,
        -90.  ]))

In [17]:
#lats,lons = tem700.latlons()
#lats,lons 这是个矩阵

In [18]:
#lats,lons 这是个矩阵

In [26]:
datasets = []
datasets1 = []
datasets2 = []
datasets3 = []
datasets4 = []
datasets5 = []
datasets6 = []
datasets7 = []
datasets8 = []
datasets9 = []
datasets10 = []
datasets11 = []
datasets12 = []
datasets13 = []
datasets14 = []
datasets15 = []
datasets16 = []
datasets17 = []
datasets18 = []
datasets19 = []
datasets20 = []
datasets21 = []
datasets22 = []
datasets23 = []
datasets24 = []
datasets25 = []
datasets26 = []
datasets27 = []
datasets28 = []
for x,y in zip(lon,lat):
        #print(x)
        #print(y)
    x_indice = np.where(lon_list == find_nearest(lon_list,x))[0]
    y_indice = np.where(lat_list== find_nearest(lat_list,y))[0]
    #print(x_indice)
    #print(y_indice)
    #print(pbl.shape)
    #print(lts.shape)
    PBLH=np.around(pblhv[y_indice,x_indice][0], decimals=2)
    LTS=np.around(lts[y_indice,x_indice][0], decimals=2)
    #TEMS=np.around(temsv[y_indice,x_indice][0], decimals=2)
    PTEMS=np.around(ptemsv[y_indice,x_indice][0], decimals=2)-273.15
    PTEM700=np.around(ptem700v[y_indice,x_indice][0], decimals=2)-273.15
    TD2=np.around(TD2v[y_indice,x_indice][0], decimals=2)-273.15
    RH2=np.around(RH2v[y_indice,x_indice][0], decimals=2)
    SH2=np.around(Sh2v[y_indice,x_indice][0], decimals=2)
    PW=np.around(Pwv[y_indice,x_indice][0], decimals=2)
    PR=np.around(Prv[y_indice,x_indice][0], decimals=2)
    CAPE=np.around(Capev[y_indice,x_indice][0], decimals=2)
    SRH=np.around(Srhv[y_indice,x_indice][0], decimals=2)
    TOZONE=np.around(Tozonev[y_indice,x_indice][0], decimals=2)
    LSM=np.around(LSMv[y_indice,x_indice][0], decimals=2)
    B4LI=np.around(B4liv[y_indice,x_indice][0], decimals=2)
    SLI=np.around(Sliv[y_indice,x_indice][0], decimals=2)
    ST0=np.around(ST0v[y_indice,x_indice][0], decimals=2)
    GH1000=np.around(Gh1000v[y_indice,x_indice][0], decimals=2)
    GH850=np.around(Gh850v[y_indice,x_indice][0], decimals=2)
    GH700=np.around(Gh700v[y_indice,x_indice][0], decimals=2)
    GH500=np.around(Gh500v[y_indice,x_indice][0], decimals=2)
    TSURF=np.around(Tsurfv[y_indice,x_indice][0], decimals=2)-273.15
    T1000=np.around(T1000v[y_indice,x_indice][0], decimals=2)-273.15
    T850=np.around(T850v[y_indice,x_indice][0], decimals=2)-273.15
    T700=np.around(T700v[y_indice,x_indice][0], decimals=2)-273.15
    T500=np.around(T500v[y_indice,x_indice][0], decimals=2)-273.15
    CIN0=np.around(CIN0v[y_indice,x_indice][0], decimals=2)
    CIN180=np.around(CIN180v[y_indice,x_indice][0], decimals=2)
    CIN255=np.around(CIN255v[y_indice,x_indice][0], decimals=2)
    datasets.append(PBLH)
    datasets1.append(LTS)
    #datasets2.append(TEMS)
    datasets3.append(PTEMS)
    datasets4.append(PTEM700)
    datasets5.append(TD2)
    datasets6.append(RH2)
    datasets7.append(SH2)
    datasets8.append(PW)
    datasets9.append(PR)
    datasets10.append(CAPE)
    datasets11.append(SRH)
    datasets12.append(TOZONE)
    datasets13.append(LSM)
    datasets14.append(B4LI)
    datasets15.append(SLI)
    datasets16.append(ST0)
    datasets17.append(GH1000)
    datasets18.append(GH850)
    datasets19.append(GH700)
    datasets20.append(GH500)
    datasets21.append(TSURF)
    datasets22.append(T1000)
    datasets23.append(T850)
    datasets24.append(T700)
    datasets25.append(T500)
    datasets26.append(CIN0)
    datasets27.append(CIN180)
    datasets28.append(CIN255)
print(len(datasets))
print(len(datasets1))
#print(len(datasets2))
print(len(datasets3))
print(len(datasets4))
#df["PBLH"],df['LCT']=datasets,datasets1
#df.to_csv("test.csv",index=True,sep=',')

3057
3057
3057
3057

In [27]:
df["PBLH"],df['LTS'],df['PTEMS'],df['PTEM700'],df["TD2"],df["RH2"],df['SH2'],df['PW'],df['PR'],\
df["CAPE"],df['SRH'],df['TOZONE'],df['LSM'],df['B4LI'],df["SLI"],df["ST0"],df['GH1000'],df['GH850'],df['GH700'],\
df["GH500"],df['TSURF'],df['T1000'],df['T850'],df['T700'],df["T500"],df["CIN0"],df['CIN180'],df['CIN255'] \
= datasets,datasets1,datasets3,datasets4,datasets5,datasets6,datasets7,datasets8,datasets9,\
  datasets10,datasets11,datasets12,datasets13,datasets14,datasets15,datasets16,datasets17,datasets18,datasets19,\
  datasets20,datasets21,datasets22,datasets23,datasets24,datasets25,datasets26,datasets27,datasets28
df.to_csv("test.csv",index=True,sep=',')

In [ ]:
#datasets1

pbl[y_indice,x_indice] this will get:
3056,22708,4384,3264,23.5881,134.1529,4288,3072,0.0,0.0,0.0,0.0,31.9,22.02,11.01,1011.0,27.5,75,-0.48,0.03,28.0,2,0,-75.3,16114,111,284,,,942,21.5,603.9,970.0,970.0,24.0,24.0,367.0,367.0,9.6,9.6,346.0,346.0,0.31,0.31,,,,,,,883.0,883.0,20.0,20.0,11.9,11.9,1189.0,1189.0,,,,,,,,,,,24.0,24.0,,,,,,,80.0,80.0,1.0,0.0087,-0.7395,0.0238,0.0232,10.61,30.0,27.85,27.43,285.0,276.0,80.0,80.0,80.0,80.0,0.0,0.0,,,,,,,,,,,,,,[374.04],[0.62]
should call pbl[y_indice,x_indice][0]

In [ ]:
#df.to_csv("test1.csv",index=True,sep=',')

In [28]:
df.head(10)

,winNO,big_c,big_r,lat,lon,colum,row,Have,Hsd,Hmax,...,GH500,TSURF,T1000,T850,T700,T500,CIN0,CIN180,CIN225,CIN255
0,22802,4096,3264,37.3944,124.6297,4000,3264,0.0,0.0,0.0,...,5798.129883,25.050012,24.550012,17.450006,6.249994,-6.850012,-57.0,-55.0,-57.0,-57.0
1,22805,4096,3264,37.7066,124.5471,4000,3168,0.0,6.0,143.0,...,5796.370117,23.350000,24.649988,16.950006,6.249994,-7.150000,-56.0,-51.0,-56.0,-56.0
2,22806,4096,3264,37.6469,124.0689,3904,3168,0.0,0.0,0.0,...,5798.209961,26.249994,25.249994,16.749994,6.350000,-6.850012,-26.0,-30.0,-26.0,-26.0
3,22807,4096,3264,38.0790,124.9651,4096,3072,34.0,60.0,404.0,...,5793.009766,23.249994,27.149988,16.850000,6.149988,-7.549994,-11.0,-12.0,-11.0,-11.0
4,22808,4096,3264,38.0190,124.4641,4000,3072,1.0,8.0,134.0,...,5794.370117,23.450006,24.950006,16.850000,6.249994,-7.449988,-42.0,-47.0,-42.0,-42.0
5,22809,4096,3264,37.9589,123.9830,3904,3072,0.0,0.0,0.0,...,5796.290039,25.950006,25.149988,16.649988,6.450006,-7.150000,-24.0,-27.0,-24.0,-24.0
6,22901,3808,3264,37.2766,123.6943,3808,3264,0.0,0.0,0.0,...,5803.209961,28.149988,26.050012,17.149988,6.850000,-5.949988,-20.0,-20.0,-20.0,-20.0
7,22902,3808,3264,37.2183,123.2483,3712,3264,0.0,0.0,0.0,...,5805.890137,26.950006,25.850000,17.050012,6.850000,-5.650000,-28.0,-23.0,-28.0,-28.0
8,22903,3808,3264,37.1595,122.8148,3616,3264,0.0,0.0,0.0,...,5808.490234,24.850000,24.950006,17.149988,6.749994,-5.850012,-40.0,-44.0,-40.0,-40.0
9,22904,3808,3264,37.5887,123.6069,3808,3168,0.0,0.0,0.0,...,5802.689941,27.450006,26.050012,16.850000,6.550012,-6.250006,-24.0,-25.0,-24.0,-24.0