In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib import cm as CM
from matplotlib.colors import LogNorm,PowerNorm
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.io.shapereader import Reader
import matplotlib.ticker as mticker
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
from shapely.geometry import *
from scipy.interpolate import griddata
import cmocean

In [3]:
fp = "D:/data/map/JingJinJi.shp" #生成的坐标不对
mapfile = gpd.read_file(fp,encoding='gbk')

In [4]:
mapfile

,ID_0,ISO,NAME_0,ID_1,NAME_1,ID_2,NAME_2,VARNAME_2,NL_NAME_2,HASC_2,CC_2,TYPE_2,ENGTYPE_2,VALIDFR_2,VALIDTO_2,REMARKS_2,Shape_Leng,Shape_Area,geometry
0,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,8.680381,2.319570,"POLYGON ((115.545022 39.79926200000011, 115.53..."
1,45,CHN,China,580,Hebei,9854,Cangzhou,Cangzhou,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,8.282873,1.461745,"POLYGON ((116.426026 38.53540400000003, 116.42..."
2,45,CHN,China,580,Hebei,9855,Chengde,Ch锟絥gd?,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,13.869020,4.248815,"POLYGON ((117.815018 42.56875100000008, 117.82..."
3,45,CHN,China,580,Hebei,9856,Handan,H锟絥dan,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,6.557347,1.213617,"POLYGON ((114.0218660000002 36.88081, 114.0330..."
4,45,CHN,China,580,Hebei,9857,Hengshui,H锟絥gshui,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,5.675770,0.903154,"POLYGON ((115.777259 38.35769900000008, 115.78..."
5,45,CHN,China,580,Hebei,9858,Langfang,L锟絥gf锟絥g,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,6.276960,0.667687,"(POLYGON ((116.700279 39.59049500000015, 116.7..."
6,45,CHN,China,580,Hebei,9859,Qinhuangdao,Q锟絥hu锟絥gdao,????,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,5.536911,0.820913,"POLYGON ((119.1948020000001 40.60266899999999,..."
7,45,CHN,China,580,Hebei,9860,Shijiazhuang,Sh锟絡iazhuang,????,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,6.605098,1.444423,"POLYGON ((113.8118440000001 38.75784700000003,..."
8,45,CHN,China,580,Hebei,9861,Tangshan,T锟絥gshan,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,8.184939,1.396392,(POLYGON ((118.5623630000001 38.97625000000011...
9,45,CHN,China,580,Hebei,9862,Xingtai,X锟絥gt锟絠,???,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,6.145148,1.266301,"POLYGON ((115.200599 37.74150100000008, 115.20..."
10,45,CHN,China,580,Hebei,9863,Zhangjiakou,Zhangjiakou,????,None,None,D锟絡锟絪h?,Prefecture City,Unknown,Present,None,12.706990,3.920882,"POLYGON ((114.8433830000001 42.10531000000009,..."
11,45,CHN,China,572,Beijing,572,Beijing,None,None,None,None,None,None,Unknown,Present,None,8.644659,1.734891,"POLYGON ((116.666885 40.97671099999997, 116.66..."
12,45,CHN,China,598,Tianjing,598,Tianjing,None,None,None,None,None,None,Unknown,Present,None,7.871020,1.221815,"POLYGON ((117.4447699999999 40.24477999999999,..."

In [5]:
data = pd.read_csv('C:/Users/xigrug/Desktop/CCN/avg_CCNnew.csv', sep=',',skiprows=0,header=0)

In [6]:
data

,lat_bin,lon_bin,BJC,AMR_lowest,AMR_surf,AOD,B4LI,CAPE,CAPE_lowest,CAPE_nc,...,satz,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid
0,26.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2121.000000,...,-12.100,14.905000,NaN,NaN,NaN,363.000000,1.000000,363.500000,1203.500000,26.0117.5
1,26.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2048.666667,...,-8.220,15.370000,NaN,NaN,NaN,592.666667,0.996667,594.666667,1170.333333,26.0118.0
2,26.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,-4.830,15.755000,NaN,NaN,NaN,452.500000,1.000000,452.500000,1102.500000,26.0118.5
3,26.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,-0.480,16.260000,NaN,NaN,NaN,171.000000,1.000000,171.000000,1101.000000,26.0119.0
4,26.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2121.000000,...,-12.100,14.930000,NaN,NaN,NaN,1885.000000,1.000000,1885.000000,1208.000000,26.5117.5
5,26.5,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2012.500000,...,-7.735,15.450000,NaN,NaN,NaN,596.500000,1.000000,596.500000,1158.000000,26.5118.0
6,26.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-3.375,15.940000,NaN,NaN,NaN,477.000000,0.980000,491.500000,1106.500000,26.5118.5
7,26.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-0.475,16.280000,NaN,NaN,NaN,584.500000,1.000000,584.500000,1105.500000,26.5119.0
8,27.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,1904.000000,...,-6.280,15.655000,NaN,NaN,NaN,3658.000000,1.000000,3659.000000,3304.500000,27.0118.0
9,27.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-3.380,15.995000,NaN,NaN,NaN,1297.500000,1.000000,1298.500000,3303.500000,27.0118.5
10,27.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,-0.480,16.310000,NaN,NaN,NaN,718.000000,1.000000,718.000000,3301.000000,27.0119.0
11,27.0,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.20,812.0,NaN,941.000000,...,28.890,19.910000,NaN,NaN,NaN,1652.000000,1.000000,1652.000000,709.000000,27.0123.0
12,27.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.60,1119.0,NaN,667.000000,...,48.060,23.200000,NaN,NaN,NaN,891.000000,1.010000,880.000000,501.000000,27.0126.5
13,27.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,...,-12.100,15.050000,NaN,NaN,NaN,2395.000000,0.985000,2449.500000,4505.000000,27.5117.0
14,27.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2323.000000,...,-9.190,15.395000,NaN,NaN,NaN,3088.000000,1.170000,2728.000000,4504.000000,27.5117.5
15,27.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1904.000000,...,-0.480,16.355000,NaN,NaN,NaN,2999.000000,0.975000,3064.000000,3305.500000,27.5118.5
16,27.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1631.000000,...,2.470,16.690000,NaN,NaN,NaN,3058.000000,1.000000,3059.500000,3207.500000,27.5119.0
17,27.5,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,28.890,19.930000,NaN,NaN,NaN,788.000000,0.950000,833.000000,2903.000000,27.5123.0
18,27.5,123.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.80,559.0,NaN,749.000000,...,31.900,20.360000,NaN,NaN,NaN,296.000000,1.000000,296.000000,1805.000000,27.5123.5
19,28.0,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,...,-12.100,15.120000,NaN,NaN,NaN,3786.000000,1.000000,3777.000000,5605.000000,28.0117.0
20,28.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2094.500000,...,-7.735,15.630000,NaN,NaN,NaN,5353.000000,1.000000,5353.000000,5555.000000,28.0117.5
21,28.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2081.000000,...,-4.830,15.915000,NaN,NaN,NaN,5609.000000,0.920000,6080.500000,5502.500000,28.0118.0
22,28.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,2081.000000,...,-0.480,16.440000,NaN,NaN,NaN,2661.500000,0.945000,2799.500000,5502.500000,28.0118.5
23,28.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1551.000000,...,2.470,16.750000,NaN,NaN,NaN,411.000000,0.970000,422.000000,5403.000000,28.0119.0
24,28.0,119.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.90,1670.0,NaN,1551.000000,...,8.270,17.410000,NaN,NaN,NaN,827.000000,1.000000,827.000000,5401.000000,28.0119.5
25,28.0,122.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,28.890,19.980000,NaN,NaN,NaN,1010.000000,0.720000,1405.000000,2909.000000,28.0122.5
26,28.0,125.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,43.760,22.390000,NaN,NaN,NaN,4333.000000,0.870000,4990.000000,2706.000000,28.0125.5
27,28.0,126.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,45.900,22.810000,NaN,NaN,NaN,3949.000000,0.910000,4326.000000,2705.000000,28.0126.0
28,28.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.90,515.0,NaN,667.000000,...,48.060,23.250000,NaN,NaN,NaN,2808.500000,0.960000,2949.000000,2702.500000,28.0126.5
29,28.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-2.10,752.0,NaN,1621.666667,...,-10.160,15.426667,NaN,NaN,NaN,6812.000000,1.000000,6812.000000,6338.666667,28.5117.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76906,35.0,123.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2033.0,NaN,1075.000000,...,2.460,29.740000,NaN,NaN,NaN,845.000000,1.000000,845.000000,42803.000000,35.0123.5
76907,35.0,124.0,2018-08-30 04:42:00,NaN,NaN,NaN,-5.40,2061.0,NaN,1075.000000,...,5.360,29.970000,NaN,NaN,NaN,675.000000,1.000000,675.000000,42802.000000,35.0124.0
76908,35.0,124.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.80,1686.0,NaN,1242.000000,...,11.180,30.440000,NaN,NaN,NaN,1112.000000,1.000000,1112.000000,42703.000000,35.0124.5
76909,35.0,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.65,1711.5,NaN,1276.000000,...,14.100,30.565000,NaN,NaN,NaN,2437.000000,1.000000,2437.000000,41605.000000,35.0125.0
76910,35.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1320.0,NaN,1864.000000,...,22.930,31.240000,NaN,NaN,NaN,1782.000000,1.000000,1782.000000,40408.000000,35.0126.5
76911,35.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.60,1222.0,NaN,1373.000000,...,34.940,32.280000,NaN,NaN,NaN,78.000000,1.000000,78.000000,40304.000000,35.0128.5
76912,35.5,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.20,1377.0,NaN,1170.000000,...,-12.110,29.370000,NaN,NaN,NaN,661.000000,1.000000,661.000000,45202.000000,35.5121.0
76913,35.5,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1425.0,NaN,1242.000000,...,14.100,30.910000,NaN,NaN,NaN,2670.000000,1.000000,2670.000000,42705.000000,35.5125.0
76914,35.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1221.0,NaN,1408.000000,...,22.920,31.460000,NaN,NaN,NaN,3193.000000,1.000000,3193.000000,42602.000000,35.5126.5
76915,35.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.25,1838.0,NaN,1629.500000,...,34.940,32.595000,NaN,NaN,NaN,3678.000000,1.000000,3683.000000,41404.000000,35.5128.5
76916,35.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.60,1750.0,NaN,1594.000000,...,37.500,33.010000,NaN,NaN,NaN,556.000000,1.000000,557.000000,42403.000000,35.5129.0
76917,36.0,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,517.5,NaN,1170.000000,...,-12.110,29.735000,NaN,NaN,NaN,1930.000000,0.960000,1943.000000,45206.500000,36.0121.0
76918,36.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.40,1316.0,NaN,1408.000000,...,25.900,32.190000,NaN,NaN,NaN,4450.000000,0.970000,4571.000000,42607.000000,36.0127.0
76919,36.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.15,1333.5,NaN,1886.000000,...,28.885,32.370000,NaN,NaN,NaN,2245.500000,0.940000,2421.000000,42507.500000,36.0127.5
76920,36.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1779.0,NaN,1886.000000,...,31.900,32.690000,NaN,NaN,NaN,3705.500000,1.000000,3709.500000,42506.500000,36.0128.0
76921,36.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1754.0,NaN,1886.000000,...,34.940,32.920000,NaN,NaN,NaN,4548.000000,1.000000,4548.000000,42504.000000,36.0128.5
76922,36.5,121.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.75,300.5,NaN,1142.500000,...,-7.745,30.180000,NaN,NaN,NaN,2487.500000,0.995000,2494.000000,45158.000000,36.5121.5
76923,36.5,122.0,2018-08-30 04:42:00,NaN,NaN,NaN,-1.70,0.0,NaN,1115.000000,...,-3.380,30.500000,NaN,NaN,NaN,730.000000,1.000000,730.000000,45108.000000,36.5122.0
76924,36.5,122.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.80,0.0,NaN,1115.000000,...,-0.480,30.710000,NaN,NaN,NaN,747.000000,1.000000,747.000000,45107.000000,36.5122.5
76925,36.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1328.5,NaN,246.000000,...,25.900,32.525000,NaN,NaN,NaN,1799.500000,1.000000,1799.000000,44802.500000,36.5126.5
76926,36.5,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1485.0,NaN,1437.000000,...,28.890,32.710000,NaN,NaN,NaN,4552.000000,0.980000,4644.000000,44703.000000,36.5127.0
76927,36.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1536.0,NaN,1886.000000,...,34.940,33.140000,NaN,NaN,NaN,2820.000000,0.980000,2879.000000,42507.000000,36.5128.5
76928,36.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.00,1457.0,NaN,1314.000000,...,37.490,33.650000,NaN,NaN,NaN,1772.000000,1.000000,1776.000000,44603.000000,36.5129.0
76929,36.5,129.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2236.0,NaN,1594.000000,...,39.560,33.700000,NaN,NaN,NaN,563.000000,0.920000,613.000000,42408.000000,36.5129.5
76930,37.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,192.0,NaN,246.000000,...,25.900,32.870000,NaN,NaN,NaN,4359.000000,0.990000,4399.000000,44807.000000,37.0126.5
76931,37.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1302.5,NaN,1437.000000,...,28.890,33.040000,NaN,NaN,NaN,4474.500000,0.935000,4724.500000,44707.500000,37.0127.0
76932,37.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1567.5,NaN,1437.000000,...,31.900,33.350000,NaN,NaN,NaN,4152.000000,0.925000,4449.000000,44706.500000,37.0127.5
76933,37.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,781.0,NaN,1437.000000,...,34.940,33.790000,NaN,NaN,NaN,7740.000000,1.000000,7740.000000,44707.000000,37.0128.0
76934,37.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,825.0,NaN,1437.000000,...,34.940,33.570000,NaN,NaN,NaN,5428.000000,1.000000,5428.000000,44704.000000,37.0128.5
76935,37.0,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.80,1380.0,NaN,1314.000000,...,37.490,33.870000,NaN,NaN,NaN,3439.000000,1.000000,3456.000000,44606.000000,37.0129.0

In [7]:
data['Coordinates'] = list(zip(data.lon_bin, data.lat_bin))
data['Coordinates'] = data['Coordinates'].apply(Point)

In [8]:
# get geo data
gdf = gpd.GeoDataFrame(data, geometry='Coordinates')
gdf.crs = mapfile.crs
#gdf=gdf.dropna(subset=[ '2001'])#Remember to reassign
cities_with_country = gpd.sjoin(mapfile,gdf,how="inner", op='intersects')
#print(df1)
#df1.to_csv("cities_with_country.csv")

In [9]:
gdf

,lat_bin,lon_bin,BJC,AMR_lowest,AMR_surf,AOD,B4LI,CAPE,CAPE_lowest,CAPE_nc,...,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid,Coordinates
0,26.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2121.000000,...,14.905000,NaN,NaN,NaN,363.000000,1.000000,363.500000,1203.500000,26.0117.5,POINT (117.5 26)
1,26.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2048.666667,...,15.370000,NaN,NaN,NaN,592.666667,0.996667,594.666667,1170.333333,26.0118.0,POINT (118 26)
2,26.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,15.755000,NaN,NaN,NaN,452.500000,1.000000,452.500000,1102.500000,26.0118.5,POINT (118.5 26)
3,26.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,...,16.260000,NaN,NaN,NaN,171.000000,1.000000,171.000000,1101.000000,26.0119.0,POINT (119 26)
4,26.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2121.000000,...,14.930000,NaN,NaN,NaN,1885.000000,1.000000,1885.000000,1208.000000,26.5117.5,POINT (117.5 26.5)
5,26.5,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2012.500000,...,15.450000,NaN,NaN,NaN,596.500000,1.000000,596.500000,1158.000000,26.5118.0,POINT (118 26.5)
6,26.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,15.940000,NaN,NaN,NaN,477.000000,0.980000,491.500000,1106.500000,26.5118.5,POINT (118.5 26.5)
7,26.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,16.280000,NaN,NaN,NaN,584.500000,1.000000,584.500000,1105.500000,26.5119.0,POINT (119 26.5)
8,27.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,1904.000000,...,15.655000,NaN,NaN,NaN,3658.000000,1.000000,3659.000000,3304.500000,27.0118.0,POINT (118 27)
9,27.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,15.995000,NaN,NaN,NaN,1297.500000,1.000000,1298.500000,3303.500000,27.0118.5,POINT (118.5 27)
10,27.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,...,16.310000,NaN,NaN,NaN,718.000000,1.000000,718.000000,3301.000000,27.0119.0,POINT (119 27)
11,27.0,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.20,812.0,NaN,941.000000,...,19.910000,NaN,NaN,NaN,1652.000000,1.000000,1652.000000,709.000000,27.0123.0,POINT (123 27)
12,27.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.60,1119.0,NaN,667.000000,...,23.200000,NaN,NaN,NaN,891.000000,1.010000,880.000000,501.000000,27.0126.5,POINT (126.5 27)
13,27.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,...,15.050000,NaN,NaN,NaN,2395.000000,0.985000,2449.500000,4505.000000,27.5117.0,POINT (117 27.5)
14,27.5,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2323.000000,...,15.395000,NaN,NaN,NaN,3088.000000,1.170000,2728.000000,4504.000000,27.5117.5,POINT (117.5 27.5)
15,27.5,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1904.000000,...,16.355000,NaN,NaN,NaN,2999.000000,0.975000,3064.000000,3305.500000,27.5118.5,POINT (118.5 27.5)
16,27.5,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1631.000000,...,16.690000,NaN,NaN,NaN,3058.000000,1.000000,3059.500000,3207.500000,27.5119.0,POINT (119 27.5)
17,27.5,123.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,19.930000,NaN,NaN,NaN,788.000000,0.950000,833.000000,2903.000000,27.5123.0,POINT (123 27.5)
18,27.5,123.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.80,559.0,NaN,749.000000,...,20.360000,NaN,NaN,NaN,296.000000,1.000000,296.000000,1805.000000,27.5123.5,POINT (123.5 27.5)
19,28.0,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,...,15.120000,NaN,NaN,NaN,3786.000000,1.000000,3777.000000,5605.000000,28.0117.0,POINT (117 28)
20,28.0,117.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2094.500000,...,15.630000,NaN,NaN,NaN,5353.000000,1.000000,5353.000000,5555.000000,28.0117.5,POINT (117.5 28)
21,28.0,118.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2081.000000,...,15.915000,NaN,NaN,NaN,5609.000000,0.920000,6080.500000,5502.500000,28.0118.0,POINT (118 28)
22,28.0,118.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,2081.000000,...,16.440000,NaN,NaN,NaN,2661.500000,0.945000,2799.500000,5502.500000,28.0118.5,POINT (118.5 28)
23,28.0,119.0,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1551.000000,...,16.750000,NaN,NaN,NaN,411.000000,0.970000,422.000000,5403.000000,28.0119.0,POINT (119 28)
24,28.0,119.5,2013-06-01 05:09:00,NaN,NaN,NaN,-4.90,1670.0,NaN,1551.000000,...,17.410000,NaN,NaN,NaN,827.000000,1.000000,827.000000,5401.000000,28.0119.5,POINT (119.5 28)
25,28.0,122.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,...,19.980000,NaN,NaN,NaN,1010.000000,0.720000,1405.000000,2909.000000,28.0122.5,POINT (122.5 28)
26,28.0,125.5,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,22.390000,NaN,NaN,NaN,4333.000000,0.870000,4990.000000,2706.000000,28.0125.5,POINT (125.5 28)
27,28.0,126.0,2013-06-01 05:09:00,NaN,NaN,NaN,-3.10,743.0,NaN,667.000000,...,22.810000,NaN,NaN,NaN,3949.000000,0.910000,4326.000000,2705.000000,28.0126.0,POINT (126 28)
28,28.0,126.5,2013-06-01 05:09:00,NaN,NaN,NaN,-2.90,515.0,NaN,667.000000,...,23.250000,NaN,NaN,NaN,2808.500000,0.960000,2949.000000,2702.500000,28.0126.5,POINT (126.5 28)
29,28.5,117.0,2013-06-01 05:09:00,NaN,NaN,NaN,-2.10,752.0,NaN,1621.666667,...,15.426667,NaN,NaN,NaN,6812.000000,1.000000,6812.000000,6338.666667,28.5117.0,POINT (117 28.5)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76906,35.0,123.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2033.0,NaN,1075.000000,...,29.740000,NaN,NaN,NaN,845.000000,1.000000,845.000000,42803.000000,35.0123.5,POINT (123.5 35)
76907,35.0,124.0,2018-08-30 04:42:00,NaN,NaN,NaN,-5.40,2061.0,NaN,1075.000000,...,29.970000,NaN,NaN,NaN,675.000000,1.000000,675.000000,42802.000000,35.0124.0,POINT (124 35)
76908,35.0,124.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.80,1686.0,NaN,1242.000000,...,30.440000,NaN,NaN,NaN,1112.000000,1.000000,1112.000000,42703.000000,35.0124.5,POINT (124.5 35)
76909,35.0,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.65,1711.5,NaN,1276.000000,...,30.565000,NaN,NaN,NaN,2437.000000,1.000000,2437.000000,41605.000000,35.0125.0,POINT (125 35)
76910,35.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1320.0,NaN,1864.000000,...,31.240000,NaN,NaN,NaN,1782.000000,1.000000,1782.000000,40408.000000,35.0126.5,POINT (126.5 35)
76911,35.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.60,1222.0,NaN,1373.000000,...,32.280000,NaN,NaN,NaN,78.000000,1.000000,78.000000,40304.000000,35.0128.5,POINT (128.5 35)
76912,35.5,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.20,1377.0,NaN,1170.000000,...,29.370000,NaN,NaN,NaN,661.000000,1.000000,661.000000,45202.000000,35.5121.0,POINT (121 35.5)
76913,35.5,125.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1425.0,NaN,1242.000000,...,30.910000,NaN,NaN,NaN,2670.000000,1.000000,2670.000000,42705.000000,35.5125.0,POINT (125 35.5)
76914,35.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1221.0,NaN,1408.000000,...,31.460000,NaN,NaN,NaN,3193.000000,1.000000,3193.000000,42602.000000,35.5126.5,POINT (126.5 35.5)
76915,35.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-4.25,1838.0,NaN,1629.500000,...,32.595000,NaN,NaN,NaN,3678.000000,1.000000,3683.000000,41404.000000,35.5128.5,POINT (128.5 35.5)
76916,35.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.60,1750.0,NaN,1594.000000,...,33.010000,NaN,NaN,NaN,556.000000,1.000000,557.000000,42403.000000,35.5129.0,POINT (129 35.5)
76917,36.0,121.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,517.5,NaN,1170.000000,...,29.735000,NaN,NaN,NaN,1930.000000,0.960000,1943.000000,45206.500000,36.0121.0,POINT (121 36)
76918,36.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.40,1316.0,NaN,1408.000000,...,32.190000,NaN,NaN,NaN,4450.000000,0.970000,4571.000000,42607.000000,36.0127.0,POINT (127 36)
76919,36.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.15,1333.5,NaN,1886.000000,...,32.370000,NaN,NaN,NaN,2245.500000,0.940000,2421.000000,42507.500000,36.0127.5,POINT (127.5 36)
76920,36.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1779.0,NaN,1886.000000,...,32.690000,NaN,NaN,NaN,3705.500000,1.000000,3709.500000,42506.500000,36.0128.0,POINT (128 36)
76921,36.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.90,1754.0,NaN,1886.000000,...,32.920000,NaN,NaN,NaN,4548.000000,1.000000,4548.000000,42504.000000,36.0128.5,POINT (128.5 36)
76922,36.5,121.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.75,300.5,NaN,1142.500000,...,30.180000,NaN,NaN,NaN,2487.500000,0.995000,2494.000000,45158.000000,36.5121.5,POINT (121.5 36.5)
76923,36.5,122.0,2018-08-30 04:42:00,NaN,NaN,NaN,-1.70,0.0,NaN,1115.000000,...,30.500000,NaN,NaN,NaN,730.000000,1.000000,730.000000,45108.000000,36.5122.0,POINT (122 36.5)
76924,36.5,122.5,2018-08-30 04:42:00,NaN,NaN,NaN,-1.80,0.0,NaN,1115.000000,...,30.710000,NaN,NaN,NaN,747.000000,1.000000,747.000000,45107.000000,36.5122.5,POINT (122.5 36.5)
76925,36.5,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1328.5,NaN,246.000000,...,32.525000,NaN,NaN,NaN,1799.500000,1.000000,1799.000000,44802.500000,36.5126.5,POINT (126.5 36.5)
76926,36.5,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1485.0,NaN,1437.000000,...,32.710000,NaN,NaN,NaN,4552.000000,0.980000,4644.000000,44703.000000,36.5127.0,POINT (127 36.5)
76927,36.5,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.70,1536.0,NaN,1886.000000,...,33.140000,NaN,NaN,NaN,2820.000000,0.980000,2879.000000,42507.000000,36.5128.5,POINT (128.5 36.5)
76928,36.5,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-4.00,1457.0,NaN,1314.000000,...,33.650000,NaN,NaN,NaN,1772.000000,1.000000,1776.000000,44603.000000,36.5129.0,POINT (129 36.5)
76929,36.5,129.5,2018-08-30 04:42:00,NaN,NaN,NaN,-5.30,2236.0,NaN,1594.000000,...,33.700000,NaN,NaN,NaN,563.000000,0.920000,613.000000,42408.000000,36.5129.5,POINT (129.5 36.5)
76930,37.0,126.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.20,192.0,NaN,246.000000,...,32.870000,NaN,NaN,NaN,4359.000000,0.990000,4399.000000,44807.000000,37.0126.5,POINT (126.5 37)
76931,37.0,127.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.45,1302.5,NaN,1437.000000,...,33.040000,NaN,NaN,NaN,4474.500000,0.935000,4724.500000,44707.500000,37.0127.0,POINT (127 37)
76932,37.0,127.5,2018-08-30 04:42:00,NaN,NaN,NaN,-3.50,1567.5,NaN,1437.000000,...,33.350000,NaN,NaN,NaN,4152.000000,0.925000,4449.000000,44706.500000,37.0127.5,POINT (127.5 37)
76933,37.0,128.0,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,781.0,NaN,1437.000000,...,33.790000,NaN,NaN,NaN,7740.000000,1.000000,7740.000000,44707.000000,37.0128.0,POINT (128 37)
76934,37.0,128.5,2018-08-30 04:42:00,NaN,NaN,NaN,-2.40,825.0,NaN,1437.000000,...,33.570000,NaN,NaN,NaN,5428.000000,1.000000,5428.000000,44704.000000,37.0128.5,POINT (128.5 37)
76935,37.0,129.0,2018-08-30 04:42:00,NaN,NaN,NaN,-3.80,1380.0,NaN,1314.000000,...,33.870000,NaN,NaN,NaN,3439.000000,1.000000,3456.000000,44606.000000,37.0129.0,POINT (129 37)

In [10]:
cities_with_country = gpd.sjoin(mapfile,gdf,how="inner", op='intersects')

In [11]:
cities_with_country=cities_with_country.drop(["geometry"],axis=1)

In [12]:
cities_with_country.to_csv("jjj_ccn_new.csv")

In [13]:
df=pd.read_csv("jjj_ccn_new.csv")

In [14]:
df.head()

,Unnamed: 0,ID_0,ISO,NAME_0,ID_1,NAME_1,ID_2,NAME_2,VARNAME_2,NL_NAME_2,...,satz,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid
0,0,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,...,14.10,22.46,NaN,NaN,NaN,3219.0,1.00,3219.0,38302.0,39.0116.0
1,0,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,...,39.57,27.03,86.20,54511.0,14.0,5231.0,0.88,5934.0,18208.0,39.0116.0
2,0,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,...,-6.29,19.91,NaN,NaN,NaN,3334.0,1.00,3334.0,31903.0,39.0116.0
3,0,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,...,14.10,25.14,54.93,54511.0,14.0,5944.0,1.00,5944.0,9702.0,39.5116.0
4,0,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,...,14.10,21.43,NaN,NaN,NaN,1751.0,0.97,1806.0,38305.0,39.5116.0

In [15]:
df=df.drop(["Unnamed: 0"],axis=1)

In [16]:
df

,ID_0,ISO,NAME_0,ID_1,NAME_1,ID_2,NAME_2,VARNAME_2,NL_NAME_2,HASC_2,...,satz,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,stid
0,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,14.100,22.460,NaN,NaN,NaN,3219.0,1.000,3219.0,38302.0,39.0116.0
1,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,39.570,27.030,86.20,54511.0,14.0,5231.0,0.880,5934.0,18208.0,39.0116.0
2,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,-6.290,19.910,NaN,NaN,NaN,3334.0,1.000,3334.0,31903.0,39.0116.0
3,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,14.100,25.140,54.93,54511.0,14.0,5944.0,1.000,5944.0,9702.0,39.5116.0
4,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,14.100,21.430,NaN,NaN,NaN,1751.0,0.970,1806.0,38305.0,39.5116.0
5,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,22.930,23.900,37.01,54511.0,14.0,532.0,0.940,565.0,22805.0,39.5116.0
6,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,31.900,23.710,NaN,NaN,NaN,496.0,1.000,496.0,18305.0,39.5116.0
7,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,14.100,22.670,NaN,NaN,NaN,637.0,1.000,637.0,38305.0,39.5116.0
8,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,45.900,30.760,NaN,NaN,NaN,2148.0,0.940,2276.0,29108.0,39.5116.0
9,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,-6.290,27.170,NaN,NaN,NaN,1132.0,1.040,1089.0,7706.0,39.5116.0
10,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,-6.285,19.455,NaN,NaN,NaN,4137.5,1.000,4137.5,31904.5,39.5116.0
11,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,19.970,21.490,NaN,NaN,NaN,3203.0,0.935,3359.0,42604.5,39.5115.5
12,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,34.950,35.020,NaN,NaN,NaN,3657.0,0.920,3960.0,33701.0,38.5115.0
13,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,17.040,30.350,NaN,NaN,NaN,234.0,1.000,234.0,36107.0,38.5115.0
14,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,17.040,30.580,NaN,NaN,NaN,139.0,1.000,139.0,38301.0,39.0115.0
15,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,5.360,20.585,NaN,NaN,NaN,1966.0,0.955,2130.0,38406.5,39.0114.5
16,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,41.650,34.700,NaN,NaN,NaN,2625.5,1.000,2626.0,40202.5,39.0115.0
17,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,17.030,33.010,NaN,NaN,NaN,311.0,1.000,311.0,29501.0,39.0115.0
18,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,14.110,30.340,NaN,NaN,NaN,391.0,1.000,391.0,38302.0,39.0114.5
19,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,-12.110,29.250,NaN,NaN,NaN,155.0,1.000,155.0,27602.0,39.0115.0
20,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,-3.390,28.475,NaN,NaN,NaN,1689.0,0.910,1895.5,29706.5,39.0115.0
21,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,34.950,35.240,NaN,NaN,NaN,6599.0,0.890,7391.0,33704.0,39.0115.0
22,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,-3.380,29.095,NaN,NaN,NaN,350.0,0.965,367.0,38503.5,39.0115.0
23,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,8.270,20.770,NaN,NaN,NaN,923.0,1.000,923.0,38404.0,39.0115.0
24,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,25.900,21.800,NaN,NaN,NaN,600.0,1.000,600.0,36001.0,39.0115.0
25,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,41.650,23.990,NaN,NaN,NaN,367.0,1.000,367.0,33604.0,39.0115.0
26,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,8.270,20.240,NaN,NaN,NaN,4687.0,1.000,4687.0,16404.0,39.0115.0
27,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,22.930,33.080,NaN,NaN,NaN,97.0,1.000,97.0,22808.0,39.0114.5
28,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,-6.280,29.020,NaN,NaN,NaN,981.0,0.990,986.0,38506.0,39.0114.5
29,45,CHN,China,580,Hebei,9853,Baoding,Baod锟絥g,???,NaN,...,2.460,24.030,NaN,NaN,NaN,5820.0,1.000,5820.0,18603.0,39.0114.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2464,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,45.900,28.540,NaN,NaN,NaN,686.0,0.980,701.0,13702.0,39.0117.5
2465,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,28.890,21.900,NaN,NaN,NaN,234.0,1.000,234.0,38103.0,39.0117.0
2466,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,-9.200,20.920,NaN,NaN,NaN,786.0,1.000,786.0,25407.0,39.0117.5
2467,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,2.460,26.970,NaN,NaN,NaN,1048.0,0.990,1055.0,16403.0,39.5117.0
2468,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,-6.290,21.495,NaN,NaN,NaN,457.5,0.990,466.5,27504.5,39.5117.5
2469,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,2.460,20.650,NaN,NaN,NaN,286.0,1.000,286.0,12009.0,39.5117.5
2470,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,22.930,23.740,NaN,NaN,NaN,141.0,1.000,141.0,29408.0,39.5117.5
2471,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,22.930,31.125,NaN,NaN,NaN,1763.0,1.000,1763.0,14006.5,39.5117.5
2472,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,39.560,27.410,NaN,NaN,NaN,576.5,0.995,579.5,29206.5,39.5117.5
2473,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,45.900,26.300,NaN,NaN,NaN,1267.0,1.000,1267.0,42302.0,39.5117.5
2474,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,-9.200,30.710,NaN,NaN,NaN,160.0,1.000,160.0,43004.0,39.5117.0
2475,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,22.470,24.500,NaN,NaN,NaN,2210.5,0.985,2236.5,39306.5,39.5117.5
2476,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,5.370,28.410,NaN,NaN,NaN,175.0,1.000,175.0,14208.0,39.5117.5
2477,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,-9.200,21.830,NaN,NaN,NaN,440.5,1.000,441.0,19904.0,39.5117.0
2478,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,14.100,21.050,NaN,NaN,NaN,652.0,1.000,653.0,44905.0,39.5117.5
2479,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,11.180,28.740,NaN,NaN,NaN,2455.0,1.000,2455.0,38306.0,39.5117.0
2480,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,28.890,34.050,NaN,NaN,NaN,501.0,1.000,501.0,29303.0,39.5117.0
2481,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,22.930,23.400,NaN,NaN,NaN,1031.5,1.000,1031.5,38203.5,39.5117.5
2482,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,31.900,34.465,NaN,NaN,NaN,1128.0,0.995,1130.0,29303.5,39.5117.5
2483,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,22.930,23.020,NaN,NaN,NaN,2271.0,1.000,2271.0,29408.0,39.5117.5
2484,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,5.360,29.960,NaN,NaN,NaN,1179.0,1.000,1179.0,20808.0,39.5117.5
2485,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,19.980,30.980,NaN,NaN,NaN,118.0,1.000,118.0,14009.0,39.5117.0
2486,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,11.180,20.770,NaN,NaN,NaN,143.0,0.970,147.0,44906.0,39.5117.0
2487,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,31.910,31.680,NaN,NaN,NaN,973.0,0.870,1118.0,31508.0,39.5117.5
2488,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,19.970,23.450,NaN,NaN,NaN,195.0,0.770,254.0,29409.0,39.5117.0
2489,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,14.100,29.900,NaN,NaN,NaN,405.0,1.000,407.0,29508.0,39.5117.5
2490,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,39.570,23.990,NaN,NaN,NaN,170.0,1.000,170.0,44602.0,39.0117.5
2491,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,2.460,20.170,NaN,NaN,NaN,530.0,1.000,530.0,9809.0,39.0117.5
2492,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,39.570,29.740,NaN,NaN,NaN,62.0,1.000,62.0,13808.0,39.0117.5
2493,45,CHN,China,598,Tianjing,598,Tianjing,NaN,NaN,NaN,...,11.180,21.560,NaN,NaN,NaN,166.0,0.710,233.0,14109.0,39.0117.5

In [17]:
df["Date"]=pd.to_datetime(df["BJC"].str.slice(stop=10),format="%Y-%m-%d")

In [18]:
avg_data=df.groupby(['Date']).mean()

In [19]:
avg_data.to_csv("jjj_ccn_avg_new.csv")