In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib import cm as CM
from matplotlib.colors import LogNorm,PowerNorm
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.io.shapereader import Reader
import matplotlib.ticker as mticker
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
from shapely.geometry import *
from scipy.interpolate import griddata
import cmocean

In [2]:
fp = "D:/data/map/yrd_grug.shp" #生成的坐标不对
mapfile = gpd.read_file(fp,encoding='gbk')

In [3]:
mapfile

,ID_0,ISO,NAME_0,ID_1,NAME_1,ID_2,NAME_2,VARNAME_2,NL_NAME_2,HASC_2,CC_2,TYPE_2,ENGTYPE_2,VALIDFR_2,VALIDTO_2,REMARKS_2,Shape_Leng,Shape_Area,geometry
0,45,CHN,China,602,Zhejiang,10098,Hangzhou,H锟絥gzhou,???,None,None,1,Prefecture City,Unknown,Present,None,8.960808,1.594394,"(POLYGON ((120.901786 30.23431099999999, 120.9..."
1,45,CHN,China,602,Zhejiang,10099,Huzhou,H锟絲hou,???,None,None,2,Prefecture City,Unknown,Present,None,4.316532,0.546612,"POLYGON ((119.7863470000001 31.17763800000006,..."
2,45,CHN,China,602,Zhejiang,10100,Jiaxing,Jiaxing,???,None,None,2,Prefecture City,Unknown,Present,None,3.842657,0.374464,"(POLYGON ((120.9126350000001 30.365972, 120.91..."
3,45,CHN,China,602,Zhejiang,10101,Jinhua,Jinhu?,???,None,None,2,Prefecture City,Unknown,Present,None,5.796881,1.012312,"POLYGON ((119.8508150000001 29.67336999999998,..."
4,45,CHN,China,602,Zhejiang,10103,Ningbo,N锟絥gbo,???,None,None,2,Prefecture City,Unknown,Present,None,21.595619,0.831543,(POLYGON ((121.8967970000001 29.00681200000002...
5,45,CHN,China,602,Zhejiang,10105,Shaoxing,Sh锟給xing,???,None,None,2,Prefecture City,Unknown,Present,None,4.985468,0.741576,"POLYGON ((120.918939 30.17294700000008, 120.92..."
6,45,CHN,China,602,Zhejiang,10106,Taizhou,Taizhou,???,None,None,2,Prefecture City,Unknown,Present,None,20.525320,0.874436,"(POLYGON ((121.223748 27.93375100000003, 121.2..."
7,45,CHN,China,602,Zhejiang,10108,Zhoushan,Zhoushan,???,None,None,2,Prefecture City,Unknown,Present,None,20.099991,0.115241,(POLYGON ((122.1598600000001 29.61153000000013...
8,45,CHN,China,595,Shanghai,10025,Shanghai,Shanghai,None,None,None,1,Municipality,Unknown,Present,None,14.683208,0.651445,"(POLYGON ((121.702362 30.55958400000014, 121.7..."
9,45,CHN,China,585,Jiangsu,9926,Changzhou,Changzhou,None,None,None,2,Prefecture,Unknown,Present,None,4.948216,0.417194,"POLYGON ((119.852752 32.06026500000007, 119.85..."
10,45,CHN,China,585,Jiangsu,9929,Nanjing,Nanjing,None,None,None,1,Prefecture,Unknown,Present,None,6.164651,0.628212,"POLYGON ((118.7143560000001 32.61158400000011,..."
11,45,CHN,China,585,Jiangsu,9930,Nantong,Nantong,None,None,None,2,Prefecture,Unknown,Present,None,6.354114,0.851394,"POLYGON ((120.383483 32.70652800000005, 120.38..."
12,45,CHN,China,585,Jiangsu,9932,Suzhou,Suzhou,None,None,None,2,Prefecture,Unknown,Present,None,5.796321,0.801724,"POLYGON ((120.565048 32.00230700000003, 120.58..."
13,45,CHN,China,585,Jiangsu,9933,Taizhou,Taizhou,None,None,None,2,Prefecture,Unknown,Present,None,4.997262,0.555351,"POLYGON ((119.749954 33.13395200000014, 119.75..."
14,45,CHN,China,585,Jiangsu,9934,Wuxi,Wuxi,None,None,None,2,Prefecture,Unknown,Present,None,4.754228,0.437079,"POLYGON ((120.3889080000001 31.93353400000012,..."
15,45,CHN,China,585,Jiangsu,9936,Yancheng,Yancheng,None,None,None,2,Prefecture,Unknown,Present,None,10.947030,1.488312,"(POLYGON ((120.924026 32.66013600000008, 120.9..."
16,45,CHN,China,585,Jiangsu,9937,Yangzhou,Yangzhou,None,None,None,2,Prefecture,Unknown,Present,None,4.897332,0.636659,"POLYGON ((119.563676 33.40783600000003, 119.56..."
17,45,CHN,China,585,Jiangsu,9938,Zhenjiang,Zhenjiang,None,None,None,2,Prefecture,Unknown,Present,None,3.941123,0.365249,"POLYGON ((119.847861 32.28412200000002, 119.84..."
18,45,CHN,China,571,Anhui,9764,Anqing,Anqing,None,None,None,2,Prefecture,Unknown,Present,None,6.643409,1.270232,"POLYGON ((117.0228355450245 31.25971749996273,..."
19,45,CHN,China,571,Anhui,9780,Xuancheng,Xuancheng,None,None,None,2,Prefecture,Unknown,Present,None,8.472062,1.159160,"POLYGON ((118.7146177454127 31.3238732947168, ..."
20,45,CHN,China,571,Anhui,9769,Chuzhou,Chuzhou,None,None,None,2,Prefecture,Unknown,Present,None,8.990946,1.297707,"POLYGON ((118.2171079799493 33.14130027009145,..."
21,45,CHN,China,571,Anhui,9776,Maanshan,Waanshan,None,None,None,2,Prefecture,Unknown,Present,None,4.672466,0.386470,"POLYGON ((118.3768961396452 32.03305555037338,..."
22,45,CHN,China,571,Anhui,9779,Wuhu,Wuhu,None,None,None,2,Prefecture,Unknown,Present,None,5.926112,0.567801,"POLYGON ((118.1999249402838 31.52849552544819,..."
23,45,CHN,China,571,Anhui,9768,Chizhou,Chizhou,None,None,None,2,Prefecture,Unknown,Present,None,6.111543,0.787552,"POLYGON ((117.9862261498171 30.82631531480001,..."
24,45,CHN,China,571,Anhui,9778,Tongling,Tongling,None,None,None,2,Prefecture,Unknown,Present,None,3.610885,0.279958,(POLYGON ((116.9693700301028 30.64235563490467...
25,45,CHN,China,571,Anhui,9771,Hefei,Hefei,None,None,None,1,Prefecture,Unknown,Present,None,7.426906,1.087640,"POLYGON ((117.1859819504067 32.53923204462319,..."

In [4]:
data = pd.read_csv('avg_0.5_CCN.csv', sep=',',skiprows=0,header=0)

In [5]:
data

,BJC,AMR_lowest,AMR_surf,AOD,B4LI,CAPE,CAPE_lowest,CAPE_nc,CAPE_surf,CCN_0.5_cm3,...,row,satz,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO
0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.20,2176.0,NaN,2098.500000,NaN,1280.0,...,6112.0,-16.495,14.370,NaN,NaN,NaN,524.000000,1.000000,524.000000,1252.000000
1,2013-06-01 05:09:00,NaN,NaN,NaN,-5.20,2176.0,NaN,2076.000000,NaN,1059.0,...,6016.0,-17.960,14.200,NaN,NaN,NaN,1482.000000,1.000000,1482.000000,1304.000000
2,2013-06-01 05:09:00,NaN,NaN,NaN,-5.20,2176.0,NaN,2121.000000,NaN,1069.0,...,6016.0,-15.020,14.560,NaN,NaN,NaN,991.000000,1.000000,991.000000,1206.000000
3,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2121.000000,NaN,704.0,...,6064.0,-12.100,14.905,NaN,NaN,NaN,363.000000,1.000000,363.500000,1203.500000
4,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2048.666667,NaN,866.0,...,6048.0,-8.220,15.370,NaN,NaN,NaN,592.666667,0.996667,594.666667,1170.333333
5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,NaN,1252.0,...,6112.0,-4.830,15.755,NaN,NaN,NaN,452.500000,1.000000,452.500000,1102.500000
6,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,NaN,1337.0,...,6112.0,-0.480,16.260,NaN,NaN,NaN,171.000000,1.000000,171.000000,1101.000000
7,2013-06-01 05:09:00,NaN,NaN,NaN,-6.00,2678.0,NaN,2329.500000,NaN,1247.0,...,5872.0,-17.960,14.235,NaN,NaN,NaN,1597.000000,1.000000,1596.000000,2404.000000
8,2013-06-01 05:09:00,NaN,NaN,NaN,-6.00,2678.0,NaN,2329.500000,NaN,1002.5,...,5872.0,-15.030,14.595,NaN,NaN,NaN,2717.500000,1.000000,2717.500000,2306.000000
9,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2121.000000,NaN,921.0,...,5920.0,-12.100,14.930,NaN,NaN,NaN,1885.000000,1.000000,1885.000000,1208.000000
10,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2012.500000,NaN,1406.0,...,5920.0,-7.735,15.450,NaN,NaN,NaN,596.500000,1.000000,596.500000,1158.000000
11,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,NaN,1216.0,...,5968.0,-3.375,15.940,NaN,NaN,NaN,477.000000,0.980000,491.500000,1106.500000
12,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,NaN,1338.5,...,5968.0,-0.475,16.280,NaN,NaN,NaN,584.500000,1.000000,584.500000,1105.500000
13,2013-06-01 05:09:00,NaN,NaN,NaN,-6.00,2678.0,NaN,2583.000000,NaN,3817.0,...,5632.0,-17.960,14.320,NaN,NaN,NaN,513.000000,0.890000,577.000000,3507.000000
14,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,1904.000000,NaN,1021.0,...,5776.0,-6.280,15.655,NaN,NaN,NaN,3658.000000,1.000000,3659.000000,3304.500000
15,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,NaN,1252.0,...,5776.0,-3.380,15.995,NaN,NaN,NaN,1297.500000,1.000000,1298.500000,3303.500000
16,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,NaN,3600.0,...,5824.0,-0.480,16.310,NaN,NaN,NaN,718.000000,1.000000,718.000000,3301.000000
17,2013-06-01 05:09:00,NaN,NaN,NaN,-3.20,812.0,NaN,941.000000,NaN,688.0,...,5920.0,28.890,19.910,NaN,NaN,NaN,1652.000000,1.000000,1652.000000,709.000000
18,2013-06-01 05:09:00,NaN,NaN,NaN,-3.60,1119.0,NaN,667.000000,NaN,94.0,...,6112.0,48.060,23.200,NaN,NaN,NaN,891.000000,1.010000,880.000000,501.000000
19,2013-06-01 05:09:00,NaN,NaN,NaN,-4.80,1986.0,NaN,1840.000000,NaN,1574.0,...,5536.0,-17.960,14.370,NaN,NaN,NaN,3744.000000,0.880000,4246.000000,5701.000000
20,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,NaN,1219.0,...,5584.0,-15.030,14.700,NaN,NaN,NaN,2223.500000,1.025000,2157.500000,4506.000000
21,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,NaN,2971.0,...,5584.0,-12.100,15.050,NaN,NaN,NaN,2395.000000,0.985000,2449.500000,4505.000000
22,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2108.000000,NaN,6105.0,...,5536.0,-9.190,15.420,NaN,NaN,NaN,2861.000000,1.340000,2130.000000,5601.000000
23,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1904.000000,NaN,1499.5,...,5680.0,-0.480,16.355,NaN,NaN,NaN,2999.000000,0.975000,3064.000000,3305.500000
24,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1631.000000,NaN,1247.0,...,5680.0,2.470,16.690,NaN,NaN,NaN,3058.000000,1.000000,3059.500000,3207.500000
25,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,NaN,2455.0,...,5824.0,28.890,19.930,NaN,NaN,NaN,788.000000,0.950000,833.000000,2903.000000
26,2013-06-01 05:09:00,NaN,NaN,NaN,-2.80,559.0,NaN,749.000000,NaN,605.5,...,5872.0,31.900,20.360,NaN,NaN,NaN,296.000000,1.000000,296.000000,1805.000000
27,2013-06-01 05:09:00,NaN,NaN,NaN,-4.80,1986.0,NaN,1840.000000,NaN,992.5,...,5392.0,-17.960,14.450,NaN,NaN,NaN,2560.500000,0.975000,2602.000000,5705.500000
28,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,NaN,1324.0,...,5392.0,-15.030,14.810,NaN,NaN,NaN,4444.500000,0.985000,4533.500000,5607.500000
29,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,NaN,626.0,...,5440.0,-12.100,15.120,NaN,NaN,NaN,3786.000000,1.000000,3777.000000,5605.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118452,2019-08-31 05:23:00,NaN,NaN,NaN,-1.96,530.0,NaN,310.000000,NaN,208.0,...,672.0,39.560,43.000,NaN,NaN,NaN,101.000000,1.000000,101.000000,42402.000000
118453,2019-08-31 05:23:00,NaN,NaN,NaN,-1.76,480.0,NaN,310.000000,NaN,290.0,...,672.0,41.650,43.220,NaN,NaN,NaN,324.000000,1.000000,324.000000,42401.000000
118454,2019-08-31 05:23:00,NaN,NaN,NaN,-1.66,400.0,NaN,323.000000,NaN,397.0,...,672.0,43.760,43.450,NaN,NaN,NaN,1058.000000,1.000000,1058.000000,42303.000000
118455,2019-08-31 05:23:00,NaN,NaN,NaN,-1.21,356.0,NaN,323.000000,NaN,271.0,...,624.0,45.900,43.830,NaN,NaN,NaN,280.000000,1.000000,280.000000,42303.500000
118456,2019-08-31 05:23:00,NaN,NaN,NaN,-0.56,247.0,NaN,323.000000,NaN,242.0,...,672.0,48.060,43.980,NaN,NaN,NaN,885.000000,1.000000,885.000000,42301.000000
118457,2019-08-31 05:23:00,NaN,NaN,NaN,-0.86,207.0,NaN,196.000000,NaN,379.0,...,192.0,-3.390,41.280,NaN,NaN,NaN,64.000000,1.000000,64.000000,45108.000000
118458,2019-08-31 05:23:00,NaN,NaN,NaN,-2.66,641.0,NaN,196.000000,NaN,470.0,...,192.0,-0.490,41.440,NaN,NaN,NaN,72.000000,1.000000,72.000000,45107.000000
118459,2019-08-31 05:23:00,NaN,NaN,NaN,-2.66,724.0,NaN,576.000000,NaN,405.0,...,192.0,2.460,41.610,NaN,NaN,NaN,120.000000,1.000000,120.000000,45009.000000
118460,2019-08-31 05:23:00,NaN,NaN,NaN,-2.36,600.0,NaN,576.000000,NaN,494.0,...,192.0,5.350,41.780,NaN,NaN,NaN,731.000000,1.000000,731.000000,45008.000000
118461,2019-08-31 05:23:00,NaN,NaN,NaN,-2.21,472.0,NaN,576.000000,NaN,471.0,...,240.0,8.260,41.815,NaN,NaN,NaN,917.000000,1.000000,918.000000,45005.500000
118462,2019-08-31 05:23:00,NaN,NaN,NaN,-1.91,370.5,NaN,752.000000,NaN,487.5,...,240.0,11.170,41.995,NaN,NaN,NaN,1530.500000,1.000000,1530.500000,44907.500000
118463,2019-08-31 05:23:00,NaN,NaN,NaN,-1.86,338.0,NaN,752.000000,NaN,293.0,...,288.0,14.100,42.040,NaN,NaN,NaN,1891.000000,1.000000,1891.000000,44905.000000
118464,2019-08-31 05:23:00,NaN,NaN,NaN,-1.96,408.0,NaN,321.000000,NaN,558.0,...,288.0,22.920,42.640,NaN,NaN,NaN,52.000000,1.000000,52.000000,44805.000000
118465,2019-08-31 05:23:00,NaN,NaN,NaN,-1.31,290.5,NaN,321.000000,NaN,964.5,...,336.0,25.895,42.720,NaN,NaN,NaN,145.500000,1.000000,145.500000,44802.500000
118466,2019-08-31 05:23:00,NaN,NaN,NaN,-1.76,393.0,NaN,667.000000,NaN,782.0,...,384.0,28.890,42.820,NaN,NaN,NaN,192.000000,1.000000,192.000000,44703.000000
118467,2019-08-31 05:23:00,NaN,NaN,NaN,-1.16,363.0,NaN,310.000000,NaN,369.0,...,480.0,37.500,43.310,NaN,NaN,NaN,182.000000,0.990000,184.000000,42409.000000
118468,2019-08-31 05:23:00,NaN,NaN,NaN,-0.96,327.0,NaN,310.000000,NaN,379.0,...,480.0,39.570,43.510,NaN,NaN,NaN,123.000000,0.990000,124.000000,42408.000000
118469,2019-08-31 05:23:00,NaN,NaN,NaN,-0.66,234.0,NaN,323.000000,NaN,291.0,...,576.0,48.060,44.230,NaN,NaN,NaN,820.000000,1.000000,820.000000,42304.000000
118470,2019-08-31 05:23:00,NaN,NaN,NaN,-1.36,203.0,NaN,752.000000,NaN,432.0,...,192.0,14.100,42.310,NaN,NaN,NaN,1653.000000,1.000000,1653.000000,44908.000000
118471,2019-08-31 05:23:00,NaN,NaN,NaN,-3.36,838.0,NaN,752.000000,NaN,679.0,...,192.0,17.030,42.500,NaN,NaN,NaN,546.000000,1.000000,546.000000,44907.000000
118472,2019-08-31 05:23:00,NaN,NaN,NaN,-2.96,924.0,NaN,321.000000,NaN,518.0,...,192.0,19.970,42.700,NaN,NaN,NaN,136.000000,1.000000,136.000000,44809.000000
118473,2019-08-31 05:23:00,NaN,NaN,NaN,-2.66,620.0,NaN,321.000000,NaN,429.0,...,192.0,22.920,42.900,NaN,NaN,NaN,209.000000,1.000000,209.000000,44808.000000
118474,2019-08-31 05:23:00,NaN,NaN,NaN,-1.86,393.0,NaN,321.000000,NaN,613.0,...,192.0,25.900,43.120,NaN,NaN,NaN,319.000000,1.000000,319.000000,44807.000000
118475,2019-08-31 05:23:00,NaN,NaN,NaN,-2.06,685.5,NaN,667.000000,NaN,1037.5,...,240.0,28.890,43.215,NaN,NaN,NaN,106.000000,0.965000,108.000000,44707.500000
118476,2019-08-31 05:23:00,NaN,NaN,NaN,-2.21,571.5,NaN,667.000000,NaN,465.5,...,240.0,31.900,43.460,NaN,NaN,NaN,335.000000,1.000000,335.000000,44706.500000
118477,2019-08-31 05:23:00,NaN,NaN,NaN,-1.96,547.0,NaN,513.000000,NaN,290.0,...,384.0,41.650,43.990,NaN,NaN,NaN,799.000000,1.000000,799.000000,44601.000000
118478,2019-08-31 05:23:00,NaN,NaN,NaN,-2.56,746.0,NaN,1052.000000,NaN,188.0,...,288.0,43.760,44.470,NaN,NaN,NaN,95.000000,1.000000,95.000000,44506.000000
118479,2019-08-31 05:23:00,NaN,NaN,NaN,-2.66,827.0,NaN,513.000000,NaN,131.0,...,192.0,41.650,44.500,NaN,NaN,NaN,208.000000,1.000000,208.000000,44607.000000
118480,2019-08-31 05:23:00,NaN,NaN,NaN,-2.86,863.0,NaN,1052.000000,NaN,539.0,...,192.0,43.760,44.730,NaN,NaN,NaN,46.000000,1.000000,46.000000,44509.000000
118481,2019-08-31 05:23:00,NaN,NaN,NaN,-2.76,806.0,NaN,1052.000000,NaN,215.0,...,192.0,45.900,44.970,NaN,NaN,NaN,2057.000000,1.000000,2062.000000,44508.000000

In [6]:
data['Coordinates'] = list(zip(data.lon, data.lat))
data['Coordinates'] = data['Coordinates'].apply(Point)

In [7]:
# get geo data
gdf = gpd.GeoDataFrame(data, geometry='Coordinates')
gdf.crs = mapfile.crs
#gdf=gdf.dropna(subset=[ '2001'])#Remember to reassign
cities_with_country = gpd.sjoin(mapfile,gdf,how="inner", op='intersects')
#print(df1)
#df1.to_csv("cities_with_country.csv")

In [8]:
gdf

,BJC,AMR_lowest,AMR_surf,AOD,B4LI,CAPE,CAPE_lowest,CAPE_nc,CAPE_surf,CCN_0.5_cm3,...,satz,solz,sound_D(km),sound_ID,sound_hour,sumN_0.5,sumN_0.5_sumN_1.0,sumN_1.0,winNO,Coordinates
0,2013-06-01 05:09:00,NaN,NaN,NaN,-5.20,2176.0,NaN,2098.500000,NaN,1280.0,...,-16.495,14.370,NaN,NaN,NaN,524.000000,1.000000,524.000000,1252.000000,POINT (117.22395 25.9399)
1,2013-06-01 05:09:00,NaN,NaN,NaN,-5.20,2176.0,NaN,2076.000000,NaN,1059.0,...,-17.960,14.200,NaN,NaN,NaN,1482.000000,1.000000,1482.000000,1304.000000,POINT (116.9385 26.2174)
2,2013-06-01 05:09:00,NaN,NaN,NaN,-5.20,2176.0,NaN,2121.000000,NaN,1069.0,...,-15.020,14.560,NaN,NaN,NaN,991.000000,1.000000,991.000000,1206.000000,POINT (117.3345 26.2847)
3,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2121.000000,NaN,704.0,...,-12.100,14.905,NaN,NaN,NaN,363.000000,1.000000,363.500000,1203.500000,POINT (117.76445 26.19285)
4,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,2149.0,NaN,2048.666667,NaN,866.0,...,-8.220,15.370,NaN,NaN,NaN,592.666667,0.996667,594.666667,1170.333333,POINT (118.2538333333333 26.32436666666667)
5,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,NaN,1252.0,...,-4.830,15.755,NaN,NaN,NaN,452.500000,1.000000,452.500000,1102.500000,POINT (118.74335 26.18495)
6,2013-06-01 05:09:00,NaN,NaN,NaN,-6.90,2822.0,NaN,1904.000000,NaN,1337.0,...,-0.480,16.260,NaN,NaN,NaN,171.000000,1.000000,171.000000,1101.000000,POINT (119.2955 26.2706)
7,2013-06-01 05:09:00,NaN,NaN,NaN,-6.00,2678.0,NaN,2329.500000,NaN,1247.0,...,-17.960,14.235,NaN,NaN,NaN,1597.000000,1.000000,1596.000000,2404.000000,POINT (116.80505 26.6842)
8,2013-06-01 05:09:00,NaN,NaN,NaN,-6.00,2678.0,NaN,2329.500000,NaN,1002.5,...,-15.030,14.595,NaN,NaN,NaN,2717.500000,1.000000,2717.500000,2306.000000,POINT (117.2027 26.75185)
9,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2121.000000,NaN,921.0,...,-12.100,14.930,NaN,NaN,NaN,1885.000000,1.000000,1885.000000,1208.000000,POINT (117.6345 26.66)
10,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,2012.500000,NaN,1406.0,...,-7.735,15.450,NaN,NaN,NaN,596.500000,1.000000,596.500000,1158.000000,POINT (118.20235 26.75005)
11,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,NaN,1216.0,...,-3.375,15.940,NaN,NaN,NaN,477.000000,0.980000,491.500000,1106.500000,POINT (118.80335 26.68225)
12,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,NaN,1338.5,...,-0.475,16.280,NaN,NaN,NaN,584.500000,1.000000,584.500000,1105.500000,POINT (119.17235 26.7391)
13,2013-06-01 05:09:00,NaN,NaN,NaN,-6.00,2678.0,NaN,2583.000000,NaN,3817.0,...,-17.960,14.320,NaN,NaN,NaN,513.000000,0.890000,577.000000,3507.000000,POINT (116.5805 27.4615)
14,2013-06-01 05:09:00,NaN,NaN,NaN,-6.10,2574.0,NaN,1904.000000,NaN,1021.0,...,-6.280,15.655,NaN,NaN,NaN,3658.000000,1.000000,3659.000000,3304.500000,POINT (118.26245 27.248)
15,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,NaN,1252.0,...,-3.380,15.995,NaN,NaN,NaN,1297.500000,1.000000,1298.500000,3303.500000,POINT (118.63535 27.3066)
16,2013-06-01 05:09:00,NaN,NaN,NaN,-5.30,1902.0,NaN,1904.000000,NaN,3600.0,...,-0.480,16.310,NaN,NaN,NaN,718.000000,1.000000,718.000000,3301.000000,POINT (119.0478 27.2076)
17,2013-06-01 05:09:00,NaN,NaN,NaN,-3.20,812.0,NaN,941.000000,NaN,688.0,...,28.890,19.910,NaN,NaN,NaN,1652.000000,1.000000,1652.000000,709.000000,POINT (123.1648 27.4528)
18,2013-06-01 05:09:00,NaN,NaN,NaN,-3.60,1119.0,NaN,667.000000,NaN,94.0,...,48.060,23.200,NaN,NaN,NaN,891.000000,1.010000,880.000000,501.000000,POINT (126.9995 27.2354)
19,2013-06-01 05:09:00,NaN,NaN,NaN,-4.80,1986.0,NaN,1840.000000,NaN,1574.0,...,-17.960,14.370,NaN,NaN,NaN,3744.000000,0.880000,4246.000000,5701.000000,POINT (116.4893 27.7725)
20,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,NaN,1219.0,...,-15.030,14.700,NaN,NaN,NaN,2223.500000,1.025000,2157.500000,4506.000000,POINT (116.9365 27.68555)
21,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2323.000000,NaN,2971.0,...,-12.100,15.050,NaN,NaN,NaN,2395.000000,0.985000,2449.500000,4505.000000,POINT (117.32835 27.75075)
22,2013-06-01 05:09:00,NaN,NaN,NaN,-4.60,2112.0,NaN,2108.000000,NaN,6105.0,...,-9.190,15.420,NaN,NaN,NaN,2861.000000,1.340000,2130.000000,5601.000000,POINT (117.6693 27.9672)
23,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1904.000000,NaN,1499.5,...,-0.480,16.355,NaN,NaN,NaN,2999.000000,0.975000,3064.000000,3305.500000,POINT (118.92305 27.67615)
24,2013-06-01 05:09:00,NaN,NaN,NaN,-4.30,1634.0,NaN,1631.000000,NaN,1247.0,...,2.470,16.690,NaN,NaN,NaN,3058.000000,1.000000,3059.500000,3207.500000,POINT (119.29525 27.7325)
25,2013-06-01 05:09:00,NaN,NaN,NaN,-3.00,620.0,NaN,557.000000,NaN,2455.0,...,28.890,19.930,NaN,NaN,NaN,788.000000,0.950000,833.000000,2903.000000,POINT (123.0934 27.766)
26,2013-06-01 05:09:00,NaN,NaN,NaN,-2.80,559.0,NaN,749.000000,NaN,605.5,...,31.900,20.360,NaN,NaN,NaN,296.000000,1.000000,296.000000,1805.000000,POINT (123.6221 27.67045)
27,2013-06-01 05:09:00,NaN,NaN,NaN,-4.80,1986.0,NaN,1840.000000,NaN,992.5,...,-17.960,14.450,NaN,NaN,NaN,2560.500000,0.975000,2602.000000,5705.500000,POINT (116.3529 28.23875)
28,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,NaN,1324.0,...,-15.030,14.810,NaN,NaN,NaN,4444.500000,0.985000,4533.500000,5607.500000,POINT (116.7565 28.3078)
29,2013-06-01 05:09:00,NaN,NaN,NaN,-4.70,2219.0,NaN,2108.000000,NaN,626.0,...,-12.100,15.120,NaN,NaN,NaN,3786.000000,1.000000,3777.000000,5605.000000,POINT (117.1951 28.2178)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118452,2019-08-31 05:23:00,NaN,NaN,NaN,-1.96,530.0,NaN,310.000000,NaN,208.0,...,39.560,43.000,NaN,NaN,NaN,101.000000,1.000000,101.000000,42402.000000,POINT (117.1894 48.5448)
118453,2019-08-31 05:23:00,NaN,NaN,NaN,-1.76,480.0,NaN,310.000000,NaN,290.0,...,41.650,43.220,NaN,NaN,NaN,324.000000,1.000000,324.000000,42401.000000,POINT (117.748 48.5903)
118454,2019-08-31 05:23:00,NaN,NaN,NaN,-1.66,400.0,NaN,323.000000,NaN,397.0,...,43.760,43.450,NaN,NaN,NaN,1058.000000,1.000000,1058.000000,42303.000000,POINT (118.3415 48.6347)
118455,2019-08-31 05:23:00,NaN,NaN,NaN,-1.21,356.0,NaN,323.000000,NaN,271.0,...,45.900,43.830,NaN,NaN,NaN,280.000000,1.000000,280.000000,42303.500000,POINT (118.94045 48.83485)
118456,2019-08-31 05:23:00,NaN,NaN,NaN,-0.56,247.0,NaN,323.000000,NaN,242.0,...,48.060,43.980,NaN,NaN,NaN,885.000000,1.000000,885.000000,42301.000000,POINT (119.6562 48.7226)
118457,2019-08-31 05:23:00,NaN,NaN,NaN,-0.86,207.0,NaN,196.000000,NaN,379.0,...,-3.390,41.280,NaN,NaN,NaN,64.000000,1.000000,64.000000,45108.000000,POINT (108.1903 49.0744)
118458,2019-08-31 05:23:00,NaN,NaN,NaN,-2.66,641.0,NaN,196.000000,NaN,470.0,...,-0.490,41.440,NaN,NaN,NaN,72.000000,1.000000,72.000000,45107.000000,POINT (108.6884 49.1529)
118459,2019-08-31 05:23:00,NaN,NaN,NaN,-2.66,724.0,NaN,576.000000,NaN,405.0,...,2.460,41.610,NaN,NaN,NaN,120.000000,1.000000,120.000000,45009.000000,POINT (109.1878 49.2292)
118460,2019-08-31 05:23:00,NaN,NaN,NaN,-2.36,600.0,NaN,576.000000,NaN,494.0,...,5.350,41.780,NaN,NaN,NaN,731.000000,1.000000,731.000000,45008.000000,POINT (109.6907 49.3035)
118461,2019-08-31 05:23:00,NaN,NaN,NaN,-2.21,472.0,NaN,576.000000,NaN,471.0,...,8.260,41.815,NaN,NaN,NaN,917.000000,1.000000,918.000000,45005.500000,POINT (110.2617 49.22255)
118462,2019-08-31 05:23:00,NaN,NaN,NaN,-1.91,370.5,NaN,752.000000,NaN,487.5,...,11.170,41.995,NaN,NaN,NaN,1530.500000,1.000000,1530.500000,44907.500000,POINT (110.7773 49.29565000000001)
118463,2019-08-31 05:23:00,NaN,NaN,NaN,-1.86,338.0,NaN,752.000000,NaN,293.0,...,14.100,42.040,NaN,NaN,NaN,1891.000000,1.000000,1891.000000,44905.000000,POINT (111.3647 49.2114)
118464,2019-08-31 05:23:00,NaN,NaN,NaN,-1.96,408.0,NaN,321.000000,NaN,558.0,...,22.920,42.640,NaN,NaN,NaN,52.000000,1.000000,52.000000,44805.000000,POINT (113.0439 49.4178)
118465,2019-08-31 05:23:00,NaN,NaN,NaN,-1.31,290.5,NaN,321.000000,NaN,964.5,...,25.895,42.720,NaN,NaN,NaN,145.500000,1.000000,145.500000,44802.500000,POINT (113.70165 49.33105000000001)
118466,2019-08-31 05:23:00,NaN,NaN,NaN,-1.76,393.0,NaN,667.000000,NaN,782.0,...,28.890,42.820,NaN,NaN,NaN,192.000000,1.000000,192.000000,44703.000000,POINT (114.387 49.2427)
118467,2019-08-31 05:23:00,NaN,NaN,NaN,-1.16,363.0,NaN,310.000000,NaN,369.0,...,37.500,43.310,NaN,NaN,NaN,182.000000,0.990000,184.000000,42409.000000,POINT (116.4903 49.1245)
118468,2019-08-31 05:23:00,NaN,NaN,NaN,-0.96,327.0,NaN,310.000000,NaN,379.0,...,39.570,43.510,NaN,NaN,NaN,123.000000,0.990000,124.000000,42408.000000,POINT (117.0251 49.1694)
118469,2019-08-31 05:23:00,NaN,NaN,NaN,-0.66,234.0,NaN,323.000000,NaN,291.0,...,48.060,44.230,NaN,NaN,NaN,820.000000,1.000000,820.000000,42304.000000,POINT (119.5914 49.035)
118470,2019-08-31 05:23:00,NaN,NaN,NaN,-1.36,203.0,NaN,752.000000,NaN,432.0,...,14.100,42.310,NaN,NaN,NaN,1653.000000,1.000000,1653.000000,44908.000000,POINT (111.2458 49.5206)
118471,2019-08-31 05:23:00,NaN,NaN,NaN,-3.36,838.0,NaN,752.000000,NaN,679.0,...,17.030,42.500,NaN,NaN,NaN,546.000000,1.000000,546.000000,44907.000000,POINT (111.7905 49.59)
118472,2019-08-31 05:23:00,NaN,NaN,NaN,-2.96,924.0,NaN,321.000000,NaN,518.0,...,19.970,42.700,NaN,NaN,NaN,136.000000,1.000000,136.000000,44809.000000,POINT (112.3528 49.6585)
118473,2019-08-31 05:23:00,NaN,NaN,NaN,-2.66,620.0,NaN,321.000000,NaN,429.0,...,22.920,42.900,NaN,NaN,NaN,209.000000,1.000000,209.000000,44808.000000,POINT (112.9358 49.7286)
118474,2019-08-31 05:23:00,NaN,NaN,NaN,-1.86,393.0,NaN,321.000000,NaN,613.0,...,25.900,43.120,NaN,NaN,NaN,319.000000,1.000000,319.000000,44807.000000,POINT (113.5458 49.797)
118475,2019-08-31 05:23:00,NaN,NaN,NaN,-2.06,685.5,NaN,667.000000,NaN,1037.5,...,28.890,43.215,NaN,NaN,NaN,106.000000,0.965000,108.000000,44707.500000,POINT (114.23775 49.70935)
118476,2019-08-31 05:23:00,NaN,NaN,NaN,-2.21,571.5,NaN,667.000000,NaN,465.5,...,31.900,43.460,NaN,NaN,NaN,335.000000,1.000000,335.000000,44706.500000,POINT (114.91435 49.77889999999999)
118477,2019-08-31 05:23:00,NaN,NaN,NaN,-1.96,547.0,NaN,513.000000,NaN,290.0,...,41.650,43.990,NaN,NaN,NaN,799.000000,1.000000,799.000000,44601.000000,POINT (117.5125 49.5264)
118478,2019-08-31 05:23:00,NaN,NaN,NaN,-2.56,746.0,NaN,1052.000000,NaN,188.0,...,43.760,44.470,NaN,NaN,NaN,95.000000,1.000000,95.000000,44506.000000,POINT (118.042 49.8834)
118479,2019-08-31 05:23:00,NaN,NaN,NaN,-2.66,827.0,NaN,513.000000,NaN,131.0,...,41.650,44.500,NaN,NaN,NaN,208.000000,1.000000,208.000000,44607.000000,POINT (117.3525 50.1501)
118480,2019-08-31 05:23:00,NaN,NaN,NaN,-2.86,863.0,NaN,1052.000000,NaN,539.0,...,43.760,44.730,NaN,NaN,NaN,46.000000,1.000000,46.000000,44509.000000,POINT (117.9664 50.1954)
118481,2019-08-31 05:23:00,NaN,NaN,NaN,-2.76,806.0,NaN,1052.000000,NaN,215.0,...,45.900,44.970,NaN,NaN,NaN,2057.000000,1.000000,2062.000000,44508.000000,POINT (118.623 50.2395)

In [9]:
cities_with_country = gpd.sjoin(mapfile,gdf,how="inner", op='intersects')

In [10]:
cities_with_country=cities_with_country.drop(["geometry"],axis=1)

In [11]:
cities_with_country.to_csv("yrd_ccn_new.csv")

In [12]:
df=pd.read_csv("yrd_ccn_new.csv")

C:\Users\xigrug\Anaconda3\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
df=df.drop(["Unnamed: 0"],axis=1)

In [14]:
df["Date"]=pd.to_datetime(df["BJC"].str.slice(stop=10),format="%Y-%m-%d")

In [15]:
avg_data=df.groupby(['Date']).mean()

In [16]:
avg_data.to_csv("yrd_ccn_avg_new.csv")

In [17]:
df=avg_data.dropna(subset=['CCN_1.0_cm3'])
df_2 =df[2<=df['WSPD850']]
#df =df[df['WSPD850']<2]
df_wind0=df_2[270<df_2['WDIR850']]
df_wind0=df_wind0[df_wind0['WDIR850']<=360]
print(df_wind0['CCN_1.0_cm3'].mean())
df_wind0["rih"]=df_wind0['H14_1.0']-df_wind0['Hcbs1.0']
print(df_wind0['rih'].mean())

1001.5014531126839
3892.449165318736

In [18]:
df_2 =df[2<=df['WSPD850']]
#df =df[df['WSPD850']<2]
df_wind0=df_2[0<df_2['WDIR850']]
df_wind0=df_wind0[df_wind0['WDIR850']<=90]
print(df_wind0['CCN_1.0_cm3'].mean())
df_wind0["rih"]=df_wind0['H14_1.0']-df_wind0['Hcbs1.0']
print(df_wind0['rih'].mean())

983.9102786452397
3904.1968754487552

In [19]:
df_2 =df[2<=df['WSPD850']]
#df =df[df['WSPD850']<2]
df_wind0=df_2[90<df_2['WDIR850']]
df_wind0=df_wind0[df_wind0['WDIR850']<=180]
print(df_wind0['CCN_1.0_cm3'].mean())
df_wind0["rih"]=df_wind0['H14_1.0']-df_wind0['Hcbs1.0']
print(df_wind0['rih'].mean())

934.3405291582138
3670.2925767966008

In [20]:
df_2 =df[2<=df['WSPD850']]
#df =df[df['WSPD850']<2]
df_wind0=df_2[180<df_2['WDIR850']]
df_wind0=df_wind0[df_wind0['WDIR850']<=270]
print(df_wind0['CCN_1.0_cm3'].mean())
df_wind0["rih"]=df_wind0['H14_1.0']-df_wind0['Hcbs1.0']
print(df_wind0['rih'].mean())

1075.388647914641
4008.4661410473805